import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const campgrounds = [
  // CALIFORNIA (20 campgrounds)
  {
    name: "Yosemite Pines RV Resort",
    slug: "yosemite-pines-rv-resort-ca",
    location: "Groveland, California",
    state: "California",
    description: "Family-friendly RV resort near Yosemite National Park with full hookups, pool, and activities.",
    latitude: 37.8339,
    longitude: -120.1850,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "LAUNDRY", "CAMP_STORE"],
    phone: "(209) 962-7690",
    website: "https://www.yosemitepinesrv.com",
  },
  {
    name: "Pfeiffer Big Sur State Park",
    slug: "pfeiffer-big-sur-state-park-ca",
    location: "Big Sur, California",
    state: "California",
    description: "Stunning coastal campground in Big Sur with hiking trails and ocean views.",
    latitude: 36.2441,
    longitude: -121.7847,
    amenities: ["RESTROOMS", "SHOWERS", "FIRE_PITS", "PICNIC_TABLES", "TRAILS"],
    phone: "(831) 667-2315",
  },
  {
    name: "Lake Tahoe KOA",
    slug: "lake-tahoe-koa-ca",
    location: "South Lake Tahoe, California",
    state: "California",
    description: "Mountain camping near Lake Tahoe with cabins and RV sites.",
    latitude: 38.9593,
    longitude: -119.9772,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "CAMP_STORE", "PLAYGROUND"],
    phone: "(530) 577-3693",
    website: "https://koa.com/campgrounds/lake-tahoe/",
  },
  {
    name: "Joshua Tree National Park - Jumbo Rocks",
    slug: "joshua-tree-jumbo-rocks-ca",
    location: "Joshua Tree, California",
    state: "California",
    description: "Desert camping among massive boulder formations with stunning night skies.",
    latitude: 34.0097,
    longitude: -116.0544,
    amenities: ["RESTROOMS", "FIRE_PITS", "PICNIC_TABLES", "TRAILS"],
    phone: "(760) 367-5500",
  },
  {
    name: "Sequoia National Park - Lodgepole",
    slug: "sequoia-lodgepole-ca",
    location: "Sequoia National Park, California",
    state: "California",
    description: "Camp among giant sequoia trees with access to world-famous hiking trails.",
    latitude: 36.5967,
    longitude: -118.7325,
    amenities: ["RESTROOMS", "SHOWERS", "CAMP_STORE", "FIRE_PITS", "TRAILS"],
    phone: "(559) 565-3341",
  },
  {
    name: "Pismo Coast Village RV Resort",
    slug: "pismo-coast-village-ca",
    location: "Pismo Beach, California",
    state: "California",
    description: "Beachfront RV resort with direct beach access and full amenities.",
    latitude: 35.1428,
    longitude: -120.6413,
    amenities: ["WIFI", "POOL", "HOT_TUB", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "LAUNDRY"],
    phone: "(805) 773-1811",
    website: "https://www.pismocoastvillage.com",
  },
  {
    name: "San Elijo State Beach",
    slug: "san-elijo-state-beach-ca",
    location: "Cardiff-by-the-Sea, California",
    state: "California",
    description: "Oceanfront camping with surfing, tidepools, and beach activities.",
    latitude: 33.0078,
    longitude: -117.2786,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "DUMP_STATION"],
    phone: "(760) 753-5091",
  },
  {
    name: "Morro Bay State Park",
    slug: "morro-bay-state-park-ca",
    location: "Morro Bay, California",
    state: "California",
    description: "Coastal camping with views of Morro Rock and natural sand dunes.",
    latitude: 35.3333,
    longitude: -120.8419,
    amenities: ["RESTROOMS", "SHOWERS", "FIRE_PITS", "TRAILS"],
    phone: "(805) 772-7434",
  },
  {
    name: "Catalina Island - Two Harbors",
    slug: "catalina-two-harbors-ca",
    location: "Catalina Island, California",
    state: "California",
    description: "Island camping accessible by boat with snorkeling and kayaking.",
    latitude: 33.4447,
    longitude: -118.4992,
    amenities: ["RESTROOMS", "SHOWERS", "RESTAURANT", "BEACH"],
    phone: "(310) 510-4205",
  },
  {
    name: "Anza-Borrego Desert State Park",
    slug: "anza-borrego-ca",
    location: "Borrego Springs, California",
    state: "California",
    description: "Desert wildflower viewing and hiking in California's largest state park.",
    latitude: 33.2551,
    longitude: -116.3797,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(760) 767-4205",
  },
  {
    name: "D.L. Bliss State Park",
    slug: "dl-bliss-state-park-ca",
    location: "South Lake Tahoe, California",
    state: "California",
    description: "Pristine Lake Tahoe beaches and emerald bay views.",
    latitude: 38.9878,
    longitude: -120.1061,
    amenities: ["RESTROOMS", "SHOWERS", "BEACH", "TRAILS"],
    phone: "(530) 525-3345",
  },
  {
    name: "Lassen Volcanic National Park",
    slug: "lassen-volcanic-np-ca",
    location: "Mineral, California",
    state: "California",
    description: "Volcanic landscapes with geothermal features and mountain lakes.",
    latitude: 40.4977,
    longitude: -121.4207,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(530) 595-4480",
  },
  {
    name: "Redwood National Park - Jedediah Smith",
    slug: "redwood-jedediah-smith-ca",
    location: "Crescent City, California",
    state: "California",
    description: "Camp among ancient coastal redwoods along the Smith River.",
    latitude: 41.8019,
    longitude: -124.0886,
    amenities: ["RESTROOMS", "SHOWERS", "FIRE_PITS", "TRAILS"],
    phone: "(707) 458-3018",
  },
  {
    name: "Death Valley National Park - Furnace Creek",
    slug: "death-valley-furnace-creek-ca",
    location: "Death Valley, California",
    state: "California",
    description: "Desert camping at lowest elevation in North America with unique geology.",
    latitude: 36.4573,
    longitude: -116.8697,
    amenities: ["RESTROOMS", "DUMP_STATION", "CAMP_STORE"],
    phone: "(760) 786-3200",
  },
  {
    name: "Santa Cruz KOA",
    slug: "santa-cruz-koa-ca",
    location: "Santa Cruz, California",
    state: "California",
    description: "Redwood forest camping minutes from beach boardwalk.",
    latitude: 37.0519,
    longitude: -122.0581,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "PLAYGROUND"],
    phone: "(831) 722-0551",
    website: "https://koa.com/campgrounds/santa-cruz/",
  },
  {
    name: "Ventura Beach RV Resort",
    slug: "ventura-beach-rv-resort-ca",
    location: "Ventura, California",
    state: "California",
    description: "Beachfront resort with ocean views and full hookups.",
    latitude: 34.2639,
    longitude: -119.2597,
    amenities: ["WIFI", "POOL", "HOT_TUB", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "LAUNDRY"],
    phone: "(805) 643-9137",
  },
  {
    name: "Shasta Lake RV Resort",
    slug: "shasta-lake-rv-resort-ca",
    location: "Lakehead, California",
    state: "California",
    description: "Mountain lake camping with water sports and fishing.",
    latitude: 40.9269,
    longitude: -122.3772,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "BOAT_LAUNCH"],
    phone: "(530) 238-2370",
  },
  {
    name: "Mammoth Mountain RV Park",
    slug: "mammoth-mountain-rv-park-ca",
    location: "Mammoth Lakes, California",
    state: "California",
    description: "Alpine camping near world-class skiing and hiking.",
    latitude: 37.6485,
    longitude: -118.9720,
    amenities: ["WIFI", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "LAUNDRY"],
    phone: "(760) 934-3822",
  },
  {
    name: "Pismo Sands Beach Club",
    slug: "pismo-sands-beach-club-ca",
    location: "Oceano, California",
    state: "California",
    description: "Beach dune camping with off-road vehicle access.",
    latitude: 35.0936,
    longitude: -120.6228,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH"],
    phone: "(805) 489-1657",
  },
  {
    name: "Mendocino Coast KOA",
    slug: "mendocino-coast-koa-ca",
    location: "Manchester, California",
    state: "California",
    description: "Coastal redwood forest camping with ocean access.",
    latitude: 38.9767,
    longitude: -123.6886,
    amenities: ["WIFI", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "CAMP_STORE"],
    phone: "(707) 882-2375",
  },

  // COLORADO (15 campgrounds)
  {
    name: "Garden of the Gods RV Resort",
    slug: "garden-of-the-gods-rv-resort-co",
    location: "Colorado Springs, Colorado",
    state: "Colorado",
    description: "Premium RV resort near Garden of the Gods with mountain views.",
    latitude: 38.8747,
    longitude: -104.8858,
    amenities: ["WIFI", "POOL", "HOT_TUB", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "LAUNDRY"],
    phone: "(719) 475-9450",
    website: "https://www.gardenofthegodsrvresort.com",
  },
  {
    name: "Rocky Mountain National Park - Moraine Park",
    slug: "rmnp-moraine-park-co",
    location: "Estes Park, Colorado",
    state: "Colorado",
    description: "Iconic national park camping with elk viewing and mountain hiking.",
    latitude: 40.3598,
    longitude: -105.5897,
    amenities: ["RESTROOMS", "FIRE_PITS", "PICNIC_TABLES", "TRAILS", "AMPHITHEATER"],
    phone: "(970) 586-1206",
  },
  {
    name: "Mesa Verde National Park - Morefield",
    slug: "mesa-verde-morefield-co",
    location: "Mesa Verde, Colorado",
    state: "Colorado",
    description: "Ancient cliff dwelling tours with full-service campground.",
    latitude: 37.2864,
    longitude: -108.4889,
    amenities: ["RESTROOMS", "SHOWERS", "CAMP_STORE", "RESTAURANT", "ELECTRIC_HOOKUPS", "DUMP_STATION"],
    phone: "(970) 529-4465",
  },
  {
    name: "Great Sand Dunes National Park",
    slug: "great-sand-dunes-np-co",
    location: "Mosca, Colorado",
    state: "Colorado",
    description: "Tallest sand dunes in North America with mountain backdrop.",
    latitude: 37.7309,
    longitude: -105.5943,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(719) 378-6395",
  },
  {
    name: "Durango RV Resort",
    slug: "durango-rv-resort-co",
    location: "Durango, Colorado",
    state: "Colorado",
    description: "Mountain resort near historic downtown and scenic railroad.",
    latitude: 37.2753,
    longitude: -107.8801,
    amenities: ["WIFI", "POOL", "HOT_TUB", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(970) 247-0783",
  },
  {
    name: "Aspen/Basalt KOA",
    slug: "aspen-basalt-koa-co",
    location: "Basalt, Colorado",
    state: "Colorado",
    description: "Mountain valley camping near Aspen with river access.",
    latitude: 39.3686,
    longitude: -107.0331,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "PLAYGROUND"],
    phone: "(970) 927-3532",
  },
  {
    name: "Black Canyon of the Gunnison",
    slug: "black-canyon-gunnison-co",
    location: "Gunnison, Colorado",
    state: "Colorado",
    description: "Dramatic canyon views with hiking and rock climbing.",
    latitude: 38.5753,
    longitude: -107.7416,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(970) 641-2337",
  },
  {
    name: "Vail RV Park",
    slug: "vail-rv-park-co",
    location: "Vail, Colorado",
    state: "Colorado",
    description: "Alpine camping near world-class skiing and hiking.",
    latitude: 39.6403,
    longitude: -106.3742,
    amenities: ["WIFI", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "LAUNDRY"],
    phone: "(970) 476-3738",
  },
  {
    name: "Glenwood Canyon Resort",
    slug: "glenwood-canyon-resort-co",
    location: "Glenwood Springs, Colorado",
    state: "Colorado",
    description: "Resort camping near hot springs and canyon recreation.",
    latitude: 39.5506,
    longitude: -107.3248,
    amenities: ["WIFI", "POOL", "HOT_TUB", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER"],
    phone: "(970) 945-6737",
  },
  {
    name: "Steamboat Campground",
    slug: "steamboat-campground-co",
    location: "Steamboat Springs, Colorado",
    state: "Colorado",
    description: "Mountain town camping near skiing and hot springs.",
    latitude: 40.4850,
    longitude: -106.8317,
    amenities: ["WIFI", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "LAUNDRY"],
    phone: "(970) 879-0273",
  },
  {
    name: "Buena Vista KOA",
    slug: "buena-vista-koa-co",
    location: "Buena Vista, Colorado",
    state: "Colorado",
    description: "Mountain valley camping with white water rafting nearby.",
    latitude: 38.8422,
    longitude: -106.1311,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(719) 395-8318",
  },
  {
    name: "Telluride Town Park",
    slug: "telluride-town-park-co",
    location: "Telluride, Colorado",
    state: "Colorado",
    description: "In-town camping surrounded by mountain peaks.",
    latitude: 37.9375,
    longitude: -107.8123,
    amenities: ["RESTROOMS", "SHOWERS", "PLAYGROUND"],
    phone: "(970) 728-2173",
  },
  {
    name: "Breckenridge Tiger Run RV Resort",
    slug: "breckenridge-tiger-run-co",
    location: "Breckenridge, Colorado",
    state: "Colorado",
    description: "Mountain resort near historic mining town and ski slopes.",
    latitude: 39.4817,
    longitude: -106.0384,
    amenities: ["WIFI", "HOT_TUB", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(970) 453-9690",
  },
  {
    name: "Colorado National Monument",
    slug: "colorado-national-monument-co",
    location: "Fruita, Colorado",
    state: "Colorado",
    description: "Red rock canyons and desert landscapes with scenic drives.",
    latitude: 39.0878,
    longitude: -108.7378,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(970) 858-3617",
  },
  {
    name: "Pagosa Springs RV Park",
    slug: "pagosa-springs-rv-park-co",
    location: "Pagosa Springs, Colorado",
    state: "Colorado",
    description: "Hot springs resort town with mountain recreation.",
    latitude: 37.2694,
    longitude: -107.0097,
    amenities: ["WIFI", "HOT_TUB", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "LAUNDRY"],
    phone: "(970) 731-5345",
  },

  // ARIZONA (10 campgrounds)
  {
    name: "Flagstaff KOA Journey",
    slug: "flagstaff-koa-journey-az",
    location: "Flagstaff, Arizona",
    state: "Arizona",
    description: "Mountain camping near the Grand Canyon with full amenities.",
    latitude: 35.1983,
    longitude: -111.6513,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "CAMP_STORE", "PLAYGROUND"],
    phone: "(928) 526-9926",
    website: "https://koa.com/campgrounds/flagstaff/",
  },
  {
    name: "Mather Campground - Grand Canyon",
    slug: "mather-campground-grand-canyon-az",
    location: "Grand Canyon Village, Arizona",
    state: "Arizona",
    description: "South Rim camping in Grand Canyon National Park.",
    latitude: 36.0544,
    longitude: -112.1401,
    amenities: ["RESTROOMS", "SHOWERS", "LAUNDRY", "CAMP_STORE", "FIRE_PITS"],
    phone: "(928) 638-7851",
  },
  {
    name: "Sedona RV Resort",
    slug: "sedona-rv-resort-az",
    location: "Sedona, Arizona",
    state: "Arizona",
    description: "Red rock views with luxury resort amenities.",
    latitude: 34.8697,
    longitude: -111.7610,
    amenities: ["WIFI", "POOL", "HOT_TUB", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(928) 282-6640",
  },
  {
    name: "Lost Dutchman State Park",
    slug: "lost-dutchman-state-park-az",
    location: "Apache Junction, Arizona",
    state: "Arizona",
    description: "Superstition Mountains camping with desert hiking.",
    latitude: 33.4586,
    longitude: -111.4856,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "DUMP_STATION", "TRAILS"],
    phone: "(480) 982-4485",
  },
  {
    name: "Lake Powell RV Park",
    slug: "lake-powell-rv-park-az",
    location: "Page, Arizona",
    state: "Arizona",
    description: "Desert lake camping with water sports and scenic beauty.",
    latitude: 36.9147,
    longitude: -111.4558,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(928) 645-1004",
  },
  {
    name: "Monument Valley KOA",
    slug: "monument-valley-koa-az",
    location: "Monument Valley, Arizona",
    state: "Arizona",
    description: "Iconic desert buttes and Navajo cultural experiences.",
    latitude: 36.9853,
    longitude: -110.1081,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(435) 727-3231",
  },
  {
    name: "Saguaro National Park",
    slug: "saguaro-national-park-az",
    location: "Tucson, Arizona",
    state: "Arizona",
    description: "Giant saguaro cactus forest with desert trails.",
    latitude: 32.2967,
    longitude: -111.1661,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(520) 733-5153",
  },
  {
    name: "Catalina State Park",
    slug: "catalina-state-park-az",
    location: "Tucson, Arizona",
    state: "Arizona",
    description: "Desert mountain camping with bird watching and hiking.",
    latitude: 32.4186,
    longitude: -110.9181,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "DUMP_STATION", "TRAILS"],
    phone: "(520) 628-5798",
  },
  {
    name: "Kartchner Caverns State Park",
    slug: "kartchner-caverns-az",
    location: "Benson, Arizona",
    state: "Arizona",
    description: "Cave tours with desert camping facilities.",
    latitude: 31.8372,
    longitude: -110.3478,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "DUMP_STATION"],
    phone: "(520) 586-4100",
  },
  {
    name: "Prescott Ponderosa RV Resort",
    slug: "prescott-ponderosa-rv-resort-az",
    location: "Prescott, Arizona",
    state: "Arizona",
    description: "Pine forest camping with mild climate and historic town nearby.",
    latitude: 34.5400,
    longitude: -112.4685,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "LAUNDRY"],
    phone: "(928) 445-5310",
  },

  // TEXAS (10 campgrounds)
  {
    name: "Big Bend National Park - Chisos Basin",
    slug: "big-bend-chisos-basin-tx",
    location: "Big Bend National Park, Texas",
    state: "Texas",
    description: "Desert mountain camping with incredible stargazing and hiking.",
    latitude: 29.2727,
    longitude: -103.3027,
    amenities: ["RESTROOMS", "CAMP_STORE", "TRAILS", "AMPHITHEATER"],
    phone: "(432) 477-2251",
  },
  {
    name: "Guadalupe River State Park",
    slug: "guadalupe-river-state-park-tx",
    location: "Spring Branch, Texas",
    state: "Texas",
    description: "River tubing and camping in Texas Hill Country.",
    latitude: 29.8469,
    longitude: -98.5117,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(830) 438-2656",
  },
  {
    name: "South Padre Island KOA",
    slug: "south-padre-island-koa-tx",
    location: "South Padre Island, Texas",
    state: "Texas",
    description: "Beach camping with fishing and water sports.",
    latitude: 26.1120,
    longitude: -97.1678,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "BEACH"],
    phone: "(956) 761-5665",
  },
  {
    name: "Enchanted Rock State Natural Area",
    slug: "enchanted-rock-tx",
    location: "Fredericksburg, Texas",
    state: "Texas",
    description: "Massive pink granite dome with primitive camping.",
    latitude: 30.5050,
    longitude: -98.8203,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(830) 685-3636",
  },
  {
    name: "Padre Island National Seashore",
    slug: "padre-island-national-seashore-tx",
    location: "Corpus Christi, Texas",
    state: "Texas",
    description: "Longest undeveloped barrier island with beach camping.",
    latitude: 27.4467,
    longitude: -97.3119,
    amenities: ["RESTROOMS", "BEACH", "TRAILS"],
    phone: "(361) 949-8068",
  },
  {
    name: "Lake Travis RV Resort",
    slug: "lake-travis-rv-resort-tx",
    location: "Austin, Texas",
    state: "Texas",
    description: "Hill Country lake camping near Austin.",
    latitude: 30.3900,
    longitude: -97.8947,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "BOAT_LAUNCH"],
    phone: "(512) 266-1575",
  },
  {
    name: "Palo Duro Canyon State Park",
    slug: "palo-duro-canyon-tx",
    location: "Canyon, Texas",
    state: "Texas",
    description: "Second largest canyon in US with colorful geological formations.",
    latitude: 34.9547,
    longitude: -101.6803,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(806) 488-2227",
  },
  {
    name: "Galveston Island State Park",
    slug: "galveston-island-state-park-tx",
    location: "Galveston, Texas",
    state: "Texas",
    description: "Gulf Coast beach camping with fishing and bird watching.",
    latitude: 29.1858,
    longitude: -94.9708,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH"],
    phone: "(409) 737-1222",
  },
  {
    name: "Hill Country RV Resort",
    slug: "hill-country-rv-resort-tx",
    location: "New Braunfels, Texas",
    state: "Texas",
    description: "Resort camping near Schlitterbahn and rivers.",
    latitude: 29.7030,
    longitude: -98.1245,
    amenities: ["WIFI", "POOL", "HOT_TUB", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER"],
    phone: "(830) 625-7357",
  },
  {
    name: "Matagorda Bay Nature Park",
    slug: "matagorda-bay-nature-park-tx",
    location: "Matagorda, Texas",
    state: "Texas",
    description: "Coastal camping with fishing and wildlife viewing.",
    latitude: 28.6872,
    longitude: -95.9189,
    amenities: ["RESTROOMS", "ELECTRIC_HOOKUPS", "BEACH", "BOAT_LAUNCH"],
    phone: "(979) 863-7120",
  },

  // FLORIDA (15 campgrounds)
  {
    name: "Disney's Fort Wilderness Resort",
    slug: "disneys-fort-wilderness-fl",
    location: "Orlando, Florida",
    state: "Florida",
    description: "Disney-themed camping resort with pools, activities, and transportation to parks.",
    latitude: 28.4113,
    longitude: -81.5672,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "RESTAURANT", "CAMP_STORE", "PLAYGROUND", "ACTIVITIES"],
    phone: "(407) 824-2900",
    website: "https://disneyworld.disney.go.com/resorts/campsites-at-fort-wilderness-resort/",
  },
  {
    name: "Bahia Honda State Park",
    slug: "bahia-honda-state-park-fl",
    location: "Big Pine Key, Florida",
    state: "Florida",
    description: "Tropical beach camping in the Florida Keys with snorkeling and swimming.",
    latitude: 24.6614,
    longitude: -81.2761,
    amenities: ["RESTROOMS", "SHOWERS", "BEACH", "BOAT_LAUNCH", "TRAILS"],
    phone: "(305) 872-2353",
  },
  {
    name: "Everglades National Park - Flamingo",
    slug: "everglades-flamingo-fl",
    location: "Homestead, Florida",
    state: "Florida",
    description: "Subtropical wilderness with wildlife and kayaking.",
    latitude: 25.1403,
    longitude: -80.9203,
    amenities: ["RESTROOMS", "DUMP_STATION", "BOAT_LAUNCH"],
    phone: "(305) 242-7700",
  },
  {
    name: "St. Augustine Beach KOA",
    slug: "st-augustine-beach-koa-fl",
    location: "St. Augustine, Florida",
    state: "Florida",
    description: "Historic city beach camping with family activities.",
    latitude: 29.8586,
    longitude: -81.2656,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "PLAYGROUND"],
    phone: "(904) 471-3113",
  },
  {
    name: "Ginnie Springs",
    slug: "ginnie-springs-fl",
    location: "High Springs, Florida",
    state: "Florida",
    description: "Crystal clear springs for swimming, diving, and tubing.",
    latitude: 29.8358,
    longitude: -82.8019,
    amenities: ["RESTROOMS", "SHOWERS", "CAMP_STORE", "BEACH"],
    phone: "(386) 454-7188",
  },
  {
    name: "Topsail Hill Preserve State Park",
    slug: "topsail-hill-preserve-fl",
    location: "Santa Rosa Beach, Florida",
    state: "Florida",
    description: "White sand dunes and coastal dune lakes.",
    latitude: 30.3381,
    longitude: -86.2008,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(850) 267-8330",
  },
  {
    name: "Fort De Soto Park",
    slug: "fort-de-soto-park-fl",
    location: "Tierra Verde, Florida",
    state: "Florida",
    description: "Award-winning beach camping with historic fort.",
    latitude: 27.6336,
    longitude: -82.7311,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(727) 582-2267",
  },
  {
    name: "John Pennekamp Coral Reef State Park",
    slug: "john-pennekamp-fl",
    location: "Key Largo, Florida",
    state: "Florida",
    description: "First underwater park with snorkeling and diving.",
    latitude: 25.1244,
    longitude: -80.4081,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "BOAT_LAUNCH"],
    phone: "(305) 451-6300",
  },
  {
    name: "Anastasia State Park",
    slug: "anastasia-state-park-fl",
    location: "St. Augustine, Florida",
    state: "Florida",
    description: "Ancient sand dunes with beach and nature trails.",
    latitude: 29.8539,
    longitude: -81.2697,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(904) 461-2033",
  },
  {
    name: "Henderson Beach State Park",
    slug: "henderson-beach-state-park-fl",
    location: "Destin, Florida",
    state: "Florida",
    description: "Emerald Coast beaches with sugar-white sand.",
    latitude: 30.3797,
    longitude: -86.4267,
    amenities: ["RESTROOMS", "SHOWERS", "BEACH", "TRAILS"],
    phone: "(850) 837-7550",
  },
  {
    name: "Grayton Beach State Park",
    slug: "grayton-beach-state-park-fl",
    location: "Santa Rosa Beach, Florida",
    state: "Florida",
    description: "One of America's best beaches with rare coastal dune lake.",
    latitude: 30.3272,
    longitude: -86.1525,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(850) 267-8300",
  },
  {
    name: "Ocala National Forest",
    slug: "ocala-national-forest-fl",
    location: "Silver Springs, Florida",
    state: "Florida",
    description: "Springs and forest camping with wildlife viewing.",
    latitude: 29.0336,
    longitude: -81.7464,
    amenities: ["RESTROOMS", "SHOWERS", "TRAILS", "BEACH"],
    phone: "(352) 625-2520",
  },
  {
    name: "Big Lagoon State Park",
    slug: "big-lagoon-state-park-fl",
    location: "Pensacola, Florida",
    state: "Florida",
    description: "Coastal camping with kayaking and fishing.",
    latitude: 30.3111,
    longitude: -87.4053,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS", "BOAT_LAUNCH"],
    phone: "(850) 492-1595",
  },
  {
    name: "Jonathan Dickinson State Park",
    slug: "jonathan-dickinson-state-park-fl",
    location: "Hobe Sound, Florida",
    state: "Florida",
    description: "River camping with diverse ecosystems and wildlife.",
    latitude: 27.0139,
    longitude: -80.1419,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS", "BOAT_LAUNCH"],
    phone: "(772) 546-2771",
  },
  {
    name: "Dry Tortugas National Park",
    slug: "dry-tortugas-national-park-fl",
    location: "Key West, Florida",
    state: "Florida",
    description: "Remote island camping accessible by boat or seaplane.",
    latitude: 24.6286,
    longitude: -82.8731,
    amenities: ["RESTROOMS", "BEACH"],
    phone: "(305) 242-7700",
  },

  // WASHINGTON (10 campgrounds)
  {
    name: "La Push Beach Resort",
    slug: "la-push-beach-resort-wa",
    location: "La Push, Washington",
    state: "Washington",
    description: "Oceanfront camping on the Olympic Peninsula with beach access.",
    latitude: 47.9042,
    longitude: -124.6368,
    amenities: ["RESTROOMS", "SHOWERS", "BEACH", "TRAILS"],
    phone: "(360) 374-5267",
  },
  {
    name: "Mount Rainier - Cougar Rock Campground",
    slug: "mount-rainier-cougar-rock-wa",
    location: "Ashford, Washington",
    state: "Washington",
    description: "Old-growth forest camping with views of Mount Rainier.",
    latitude: 46.7679,
    longitude: -121.7742,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS", "AMPHITHEATER"],
    phone: "(360) 569-2211",
  },
  {
    name: "San Juan Island KOA",
    slug: "san-juan-island-koa-wa",
    location: "Friday Harbor, Washington",
    state: "Washington",
    description: "Island camping with whale watching and kayaking.",
    latitude: 48.5347,
    longitude: -123.0214,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(360) 378-2992",
  },
  {
    name: "North Cascades National Park",
    slug: "north-cascades-np-wa",
    location: "Marblemount, Washington",
    state: "Washington",
    description: "Alpine wilderness with glaciers and mountain lakes.",
    latitude: 48.7718,
    longitude: -121.2985,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(360) 854-7200",
  },
  {
    name: "Lake Chelan State Park",
    slug: "lake-chelan-state-park-wa",
    location: "Chelan, Washington",
    state: "Washington",
    description: "Mountain lake camping with water sports.",
    latitude: 47.8331,
    longitude: -119.9381,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "BOAT_LAUNCH"],
    phone: "(509) 687-3710",
  },
  {
    name: "Deception Pass State Park",
    slug: "deception-pass-state-park-wa",
    location: "Oak Harbor, Washington",
    state: "Washington",
    description: "Dramatic bridge views with beach and forest camping.",
    latitude: 48.4039,
    longitude: -122.6467,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(360) 675-3767",
  },
  {
    name: "Leavenworth RV Campground",
    slug: "leavenworth-rv-campground-wa",
    location: "Leavenworth, Washington",
    state: "Washington",
    description: "Bavarian village camping with mountain activities.",
    latitude: 47.5962,
    longitude: -120.6615,
    amenities: ["WIFI", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(509) 548-7709",
  },
  {
    name: "Seaquest State Park",
    slug: "seaquest-state-park-wa",
    location: "Castle Rock, Washington",
    state: "Washington",
    description: "Near Mount St. Helens with volcanic landscapes.",
    latitude: 46.2864,
    longitude: -122.8664,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(360) 274-8633",
  },
  {
    name: "Birch Bay State Park",
    slug: "birch-bay-state-park-wa",
    location: "Blaine, Washington",
    state: "Washington",
    description: "Coastal camping near Canadian border with crabbing.",
    latitude: 48.9192,
    longitude: -122.7567,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH"],
    phone: "(360) 371-2800",
  },
  {
    name: "Yakima Sportsman State Park",
    slug: "yakima-sportsman-state-park-wa",
    location: "Yakima, Washington",
    state: "Washington",
    description: "Riverside camping with fishing and trails.",
    latitude: 46.5858,
    longitude: -120.4481,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(509) 575-2774",
  },

  // OREGON (10 campgrounds)
  {
    name: "Cannon Beach RV Resort",
    slug: "cannon-beach-rv-resort-or",
    location: "Cannon Beach, Oregon",
    state: "Oregon",
    description: "Coastal RV resort near Haystack Rock with ocean views.",
    latitude: 45.8918,
    longitude: -123.9615,
    amenities: ["WIFI", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "LAUNDRY"],
    phone: "(503) 436-2231",
    website: "https://www.cbrvresort.com",
  },
  {
    name: "Crater Lake National Park",
    slug: "crater-lake-np-or",
    location: "Crater Lake, Oregon",
    state: "Oregon",
    description: "Deepest lake in US with stunning blue waters.",
    latitude: 42.8684,
    longitude: -122.1685,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(541) 594-3000",
  },
  {
    name: "Silver Falls State Park",
    slug: "silver-falls-state-park-or",
    location: "Sublimity, Oregon",
    state: "Oregon",
    description: "Waterfalls trail with 10 waterfalls and forest camping.",
    latitude: 44.8775,
    longitude: -122.6556,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(503) 873-8681",
  },
  {
    name: "Smith Rock State Park",
    slug: "smith-rock-state-park-or",
    location: "Terrebonne, Oregon",
    state: "Oregon",
    description: "World-class rock climbing with river camping.",
    latitude: 44.3672,
    longitude: -121.1408,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(541) 548-7501",
  },
  {
    name: "Cape Lookout State Park",
    slug: "cape-lookout-state-park-or",
    location: "Tillamook, Oregon",
    state: "Oregon",
    description: "Coastal headland camping with whale watching.",
    latitude: 45.3447,
    longitude: -123.9692,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(503) 842-4981",
  },
  {
    name: "Bend/Sisters Garden RV Resort",
    slug: "bend-sisters-garden-rv-resort-or",
    location: "Sisters, Oregon",
    state: "Oregon",
    description: "Mountain resort near skiing and hiking trails.",
    latitude: 44.2907,
    longitude: -121.5492,
    amenities: ["WIFI", "POOL", "HOT_TUB", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER"],
    phone: "(541) 549-3021",
  },
  {
    name: "Wallowa Lake State Park",
    slug: "wallowa-lake-state-park-or",
    location: "Joseph, Oregon",
    state: "Oregon",
    description: "Alpine lake camping with mountain tramway.",
    latitude: 45.2700,
    longitude: -117.2106,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BOAT_LAUNCH", "TRAILS"],
    phone: "(541) 432-4185",
  },
  {
    name: "Umpqua Lighthouse State Park",
    slug: "umpqua-lighthouse-state-park-or",
    location: "Winchester Bay, Oregon",
    state: "Oregon",
    description: "Coastal dunes with lighthouse and beach access.",
    latitude: 43.6653,
    longitude: -124.1764,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(541) 271-4118",
  },
  {
    name: "Newberry National Volcanic Monument",
    slug: "newberry-volcanic-monument-or",
    location: "La Pine, Oregon",
    state: "Oregon",
    description: "Volcanic landscapes with crater lakes and lava flows.",
    latitude: 43.7233,
    longitude: -121.2358,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(541) 383-5300",
  },
  {
    name: "Harris Beach State Park",
    slug: "harris-beach-state-park-or",
    location: "Brookings, Oregon",
    state: "Oregon",
    description: "Southern Oregon coast with sea stacks and tide pools.",
    latitude: 42.0531,
    longitude: -124.2831,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(541) 469-2021",
  },

  // Add 10 more states... (continuing in next message due to length)

  // MONTANA
  {
    name: "Glacier National Park - Many Glacier",
    slug: "glacier-np-many-glacier-mt",
    location: "Browning, Montana",
    state: "Montana",
    description: "Spectacular mountain camping with glacier views and wildlife.",
    latitude: 48.7956,
    longitude: -113.6761,
    amenities: ["RESTROOMS", "FIRE_PITS", "CAMP_STORE", "TRAILS"],
    phone: "(406) 888-7800",
  },

  // WYOMING
  {
    name: "Yellowstone - Madison Campground",
    slug: "yellowstone-madison-wy",
    location: "Yellowstone National Park, Wyoming",
    state: "Wyoming",
    description: "Riverside camping near geysers and wildlife viewing areas.",
    latitude: 44.6550,
    longitude: -110.8579,
    amenities: ["RESTROOMS", "FIRE_PITS", "AMPHITHEATER", "TRAILS"],
    phone: "(307) 344-7381",
  },

  // UTAH
  {
    name: "Zion National Park - Watchman Campground",
    slug: "zion-watchman-ut",
    location: "Springdale, Utah",
    state: "Utah",
    description: "Red rock canyon camping with access to Zion's famous trails.",
    latitude: 37.2000,
    longitude: -112.9872,
    amenities: ["RESTROOMS", "ELECTRIC_HOOKUPS", "FIRE_PITS", "TRAILS", "AMPHITHEATER"],
    phone: "(435) 772-3256",
  },
  {
    name: "Moab Under Canvas",
    slug: "moab-under-canvas-ut",
    location: "Moab, Utah",
    state: "Utah",
    description: "Luxury glamping near Arches National Park with safari tents.",
    latitude: 38.7331,
    longitude: -109.7287,
    amenities: ["RESTROOMS", "SHOWERS", "RESTAURANT", "WIFI"],
    phone: "(888) 496-1148",
    website: "https://www.undercanvas.com/camps/moab/",
  },

  // MAINE
  {
    name: "Acadia National Park - Blackwoods Campground",
    slug: "acadia-blackwoods-me",
    location: "Bar Harbor, Maine",
    state: "Maine",
    description: "Forest camping near the rocky Maine coast and mountain hiking.",
    latitude: 44.3106,
    longitude: -68.2133,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS", "AMPHITHEATER"],
    phone: "(207) 288-3274",
  },

  // NORTH CAROLINA/TENNESSEE
  {
    name: "Great Smoky Mountains - Cades Cove",
    slug: "smoky-mountains-cades-cove-nc",
    location: "Townsend, Tennessee",
    state: "North Carolina",
    description: "Historic valley camping with wildlife viewing and mountain views.",
    latitude: 35.5951,
    longitude: -83.8277,
    amenities: ["RESTROOMS", "FIRE_PITS", "CAMP_STORE", "TRAILS"],
    phone: "(865) 448-4103",
  },

  // CANADA - BRITISH COLUMBIA
  {
    name: "Whistler RV Park & Campground",
    slug: "whistler-rv-park-bc",
    location: "Whistler, British Columbia",
    state: "British Columbia",
    description: "Mountain resort camping near world-class skiing and hiking.",
    latitude: 50.1163,
    longitude: -122.9574,
    amenities: ["WIFI", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "LAUNDRY"],
    phone: "(604) 905-5533",
    website: "https://whistlercamping.com",
  },
  {
    name: "Pacific Rim National Park - Green Point",
    slug: "pacific-rim-green-point-bc",
    location: "Tofino, British Columbia",
    state: "British Columbia",
    description: "Oceanfront camping on Vancouver Island with beach access and rainforest trails.",
    latitude: 49.0856,
    longitude: -125.8633,
    amenities: ["RESTROOMS", "SHOWERS", "BEACH", "TRAILS"],
    phone: "(250) 726-3500",
  },

  // CANADA - ALBERTA
  {
    name: "Banff National Park - Two Jack Lakeside",
    slug: "banff-two-jack-lakeside-ab",
    location: "Banff, Alberta",
    state: "Alberta",
    description: "Mountain lake camping with stunning Rocky Mountain views.",
    latitude: 51.2417,
    longitude: -115.5028,
    amenities: ["RESTROOMS", "FIRE_PITS", "BOAT_LAUNCH", "TRAILS"],
    phone: "(403) 762-1550",
  },
  {
    name: "Jasper National Park - Whistlers Campground",
    slug: "jasper-whistlers-ab",
    location: "Jasper, Alberta",
    state: "Alberta",
    description: "Large campground with mountain views and wildlife viewing.",
    latitude: 52.8534,
    longitude: -118.0814,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "FIRE_PITS", "PLAYGROUND", "AMPHITHEATER"],
    phone: "(780) 852-6176",
  },

  // CANADA - ONTARIO
  {
    name: "Algonquin Park - Mew Lake Campground",
    slug: "algonquin-mew-lake-on",
    location: "Whitney, Ontario",
    state: "Ontario",
    description: "Wilderness camping in Canada's iconic provincial park.",
    latitude: 45.5787,
    longitude: -78.3634,
    amenities: ["RESTROOMS", "SHOWERS", "FIRE_PITS", "TRAILS", "CANOE_RENTAL"],
    phone: "(705) 633-5572",
  },

  // CANADA - QUEBEC
  {
    name: "Parc National du Mont-Tremblant",
    slug: "mont-tremblant-national-park-qc",
    location: "Mont-Tremblant, Quebec",
    state: "Quebec",
    description: "French Canadian wilderness camping with lakes and mountains.",
    latitude: 46.5489,
    longitude: -74.6431,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS", "CANOE_RENTAL", "BEACH"],
    phone: "(819) 688-2281",
  },

  // CANADA - NOVA SCOTIA
  {
    name: "Cape Breton Highlands National Park",
    slug: "cape-breton-highlands-ns",
    location: "Ingonish, Nova Scotia",
    state: "Nova Scotia",
    description: "Coastal mountain camping with ocean views and hiking trails.",
    latitude: 46.6833,
    longitude: -60.4167,
    amenities: ["RESTROOMS", "SHOWERS", "FIRE_PITS", "TRAILS", "BEACH"],
    phone: "(902) 224-2306",
  },

  // NEW YORK (10 campgrounds)
  {
    name: "Jellystone Park Camp-Resort",
    slug: "jellystone-park-ny",
    location: "North Java, New York",
    state: "New York",
    description: "Family camping resort with activities and character appearances.",
    latitude: 42.6667,
    longitude: -78.3333,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION", "PLAYGROUND"],
    phone: "(585) 457-9644",
  },
  {
    name: "Watkins Glen State Park",
    slug: "watkins-glen-state-park-ny",
    location: "Watkins Glen, New York",
    state: "New York",
    description: "Gorge trail camping with 19 waterfalls.",
    latitude: 42.3750,
    longitude: -76.8739,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "DUMP_STATION", "TRAILS"],
    phone: "(607) 535-4511",
  },
  {
    name: "Letchworth State Park",
    slug: "letchworth-state-park-ny",
    location: "Castile, New York",
    state: "New York",
    description: "Grand Canyon of the East with waterfalls and gorge views.",
    latitude: 42.5739,
    longitude: -78.0511,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(585) 493-3600",
  },
  {
    name: "Ausable Point Campground",
    slug: "ausable-point-ny",
    location: "Peru, New York",
    state: "New York",
    description: "Lake Champlain camping with beach and water activities.",
    latitude: 44.6978,
    longitude: -73.4536,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "BOAT_LAUNCH"],
    phone: "(518) 561-7080",
  },
  {
    name: "Niagara Falls KOA",
    slug: "niagara-falls-koa-ny",
    location: "Niagara Falls, New York",
    state: "New York",
    description: "Near world-famous waterfalls with resort amenities.",
    latitude: 43.0962,
    longitude: -78.9975,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(716) 731-3150",
  },
  {
    name: "Saratoga Springs Campground",
    slug: "saratoga-springs-campground-ny",
    location: "Greenfield Center, New York",
    state: "New York",
    description: "Historic spa town camping near horse racing track.",
    latitude: 43.1328,
    longitude: -73.8867,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER"],
    phone: "(518) 584-2556",
  },
  {
    name: "Adirondack Mountains - Lake George",
    slug: "adirondack-lake-george-ny",
    location: "Lake George, New York",
    state: "New York",
    description: "Mountain lake camping with water sports and hiking.",
    latitude: 43.4267,
    longitude: -73.7125,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "BOAT_LAUNCH"],
    phone: "(518) 644-9696",
  },
  {
    name: "Allegany State Park",
    slug: "allegany-state-park-ny",
    location: "Salamanca, New York",
    state: "New York",
    description: "Large wilderness park with lakes and trails.",
    latitude: 42.0833,
    longitude: -78.7667,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS", "BEACH"],
    phone: "(716) 354-9121",
  },
  {
    name: "Robert Moses State Park",
    slug: "robert-moses-state-park-ny",
    location: "Massena, New York",
    state: "New York",
    description: "St. Lawrence River camping with fishing and boating.",
    latitude: 44.9472,
    longitude: -74.7803,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "BOAT_LAUNCH"],
    phone: "(315) 769-8663",
  },
  {
    name: "Hither Hills State Park",
    slug: "hither-hills-state-park-ny",
    location: "Montauk, New York",
    state: "New York",
    description: "Long Island beach camping near Montauk Point.",
    latitude: 41.0539,
    longitude: -71.9028,
    amenities: ["RESTROOMS", "SHOWERS", "BEACH", "TRAILS"],
    phone: "(631) 668-2554",
  },

  // MICHIGAN (8 campgrounds)
  {
    name: "Pictured Rocks National Lakeshore",
    slug: "pictured-rocks-mi",
    location: "Munising, Michigan",
    state: "Michigan",
    description: "Colorful sandstone cliffs along Lake Superior.",
    latitude: 46.5656,
    longitude: -86.3650,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS", "BEACH"],
    phone: "(906) 387-3700",
  },
  {
    name: "Sleeping Bear Dunes National Lakeshore",
    slug: "sleeping-bear-dunes-mi",
    location: "Empire, Michigan",
    state: "Michigan",
    description: "Massive sand dunes with Lake Michigan views.",
    latitude: 44.8774,
    longitude: -86.0469,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS", "BEACH"],
    phone: "(231) 326-4700",
  },
  {
    name: "Isle Royale National Park",
    slug: "isle-royale-np-mi",
    location: "Houghton, Michigan",
    state: "Michigan",
    description: "Remote island wilderness accessible by boat or seaplane.",
    latitude: 47.9959,
    longitude: -88.9092,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(906) 482-0984",
  },
  {
    name: "Tahquamenon Falls State Park",
    slug: "tahquamenon-falls-mi",
    location: "Paradise, Michigan",
    state: "Michigan",
    description: "Upper Peninsula waterfalls with wilderness camping.",
    latitude: 46.5772,
    longitude: -85.2567,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(906) 492-3415",
  },
  {
    name: "Ludington State Park",
    slug: "ludington-state-park-mi",
    location: "Ludington, Michigan",
    state: "Michigan",
    description: "Beach and dune camping with lighthouse.",
    latitude: 44.0283,
    longitude: -86.4942,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(231) 843-2423",
  },
  {
    name: "Mackinac Island State Park",
    slug: "mackinac-island-state-park-mi",
    location: "Mackinac Island, Michigan",
    state: "Michigan",
    description: "Historic island with no cars, accessible by ferry.",
    latitude: 45.8519,
    longitude: -84.6175,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(906) 847-3328",
  },
  {
    name: "Warren Dunes State Park",
    slug: "warren-dunes-state-park-mi",
    location: "Sawyer, Michigan",
    state: "Michigan",
    description: "Lake Michigan dunes with beach camping near Chicago.",
    latitude: 41.9089,
    longitude: -86.5942,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(269) 426-4013",
  },
  {
    name: "Porcupine Mountains Wilderness",
    slug: "porcupine-mountains-mi",
    location: "Ontonagon, Michigan",
    state: "Michigan",
    description: "Old-growth forest with waterfalls and Lake Superior views.",
    latitude: 46.7008,
    longitude: -89.9736,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(906) 885-5275",
  },

  // WISCONSIN (5 campgrounds)
  {
    name: "Apostle Islands National Lakeshore",
    slug: "apostle-islands-wi",
    location: "Bayfield, Wisconsin",
    state: "Wisconsin",
    description: "Island camping with sea caves and kayaking.",
    latitude: 46.9622,
    longitude: -90.8197,
    amenities: ["RESTROOMS", "TRAILS", "BEACH"],
    phone: "(715) 779-3397",
  },
  {
    name: "Devil's Lake State Park",
    slug: "devils-lake-state-park-wi",
    location: "Baraboo, Wisconsin",
    state: "Wisconsin",
    description: "Quartzite bluffs with swimming and rock climbing.",
    latitude: 43.4214,
    longitude: -89.7281,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(608) 356-8301",
  },
  {
    name: "Peninsula State Park",
    slug: "peninsula-state-park-wi",
    location: "Fish Creek, Wisconsin",
    state: "Wisconsin",
    description: "Door County camping with golf course and lighthouse.",
    latitude: 45.1681,
    longitude: -87.2528,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(920) 868-3258",
  },
  {
    name: "Wisconsin Dells KOA",
    slug: "wisconsin-dells-koa-wi",
    location: "Wisconsin Dells, Wisconsin",
    state: "Wisconsin",
    description: "Waterpark capital camping with family activities.",
    latitude: 43.6275,
    longitude: -89.7709,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(608) 254-4177",
  },
  {
    name: "Harrington Beach State Park",
    slug: "harrington-beach-state-park-wi",
    location: "Belgium, Wisconsin",
    state: "Wisconsin",
    description: "Lake Michigan camping near Milwaukee.",
    latitude: 43.4958,
    longitude: -87.8056,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(262) 285-3015",
  },

  // MINNESOTA (5 campgrounds)
  {
    name: "Voyageurs National Park",
    slug: "voyageurs-np-mn",
    location: "International Falls, Minnesota",
    state: "Minnesota",
    description: "Water-based park with island camping and northern lights.",
    latitude: 48.4200,
    longitude: -92.8367,
    amenities: ["RESTROOMS", "TRAILS", "BOAT_LAUNCH"],
    phone: "(218) 283-6600",
  },
  {
    name: "Gooseberry Falls State Park",
    slug: "gooseberry-falls-mn",
    location: "Two Harbors, Minnesota",
    state: "Minnesota",
    description: "North Shore waterfalls with Lake Superior access.",
    latitude: 47.1431,
    longitude: -91.4681,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(218) 595-7100",
  },
  {
    name: "Itasca State Park",
    slug: "itasca-state-park-mn",
    location: "Park Rapids, Minnesota",
    state: "Minnesota",
    description: "Headwaters of the Mississippi River with old-growth forest.",
    latitude: 47.2242,
    longitude: -95.2092,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(218) 699-7251",
  },
  {
    name: "Split Rock Lighthouse State Park",
    slug: "split-rock-lighthouse-mn",
    location: "Two Harbors, Minnesota",
    state: "Minnesota",
    description: "Historic lighthouse with Lake Superior camping.",
    latitude: 47.2003,
    longitude: -91.3686,
    amenities: ["RESTROOMS", "SHOWERS", "TRAILS", "BEACH"],
    phone: "(218) 595-7625",
  },
  {
    name: "Superior National Forest",
    slug: "superior-national-forest-mn",
    location: "Duluth, Minnesota",
    state: "Minnesota",
    description: "Boundary Waters wilderness with canoe camping.",
    latitude: 47.9089,
    longitude: -91.6156,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS", "BOAT_LAUNCH"],
    phone: "(218) 626-4300",
  },

  // SOUTH DAKOTA (3 campgrounds)
  {
    name: "Mount Rushmore KOA",
    slug: "mount-rushmore-koa-sd",
    location: "Hill City, South Dakota",
    state: "South Dakota",
    description: "Black Hills camping near Mount Rushmore and Crazy Horse.",
    latitude: 43.8569,
    longitude: -103.4878,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(605) 574-2525",
  },
  {
    name: "Badlands National Park - Cedar Pass",
    slug: "badlands-cedar-pass-sd",
    location: "Interior, South Dakota",
    state: "South Dakota",
    description: "Dramatic eroded buttes and prairies with bison.",
    latitude: 43.7383,
    longitude: -101.9392,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(605) 433-5361",
  },
  {
    name: "Custer State Park",
    slug: "custer-state-park-sd",
    location: "Custer, South Dakota",
    state: "South Dakota",
    description: "Wildlife viewing with bison herds and scenic drives.",
    latitude: 43.7667,
    longitude: -103.4167,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(605) 255-4515",
  },

  // NORTH DAKOTA (2 campgrounds)
  {
    name: "Theodore Roosevelt National Park",
    slug: "theodore-roosevelt-np-nd",
    location: "Medora, North Dakota",
    state: "North Dakota",
    description: "Badlands camping with wild horses and bison.",
    latitude: 46.9789,
    longitude: -103.5383,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(701) 623-4466",
  },
  {
    name: "Lake Sakakawea State Park",
    slug: "lake-sakakawea-state-park-nd",
    location: "Pick City, North Dakota",
    state: "North Dakota",
    description: "Large reservoir with fishing and water sports.",
    latitude: 47.4989,
    longitude: -101.3817,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BOAT_LAUNCH", "BEACH"],
    phone: "(701) 487-3315",
  },

  // PENNSYLVANIA (5 campgrounds)
  {
    name: "Ricketts Glen State Park",
    slug: "ricketts-glen-state-park-pa",
    location: "Benton, Pennsylvania",
    state: "Pennsylvania",
    description: "21 waterfalls trail through old-growth forest.",
    latitude: 41.3319,
    longitude: -76.2831,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(570) 477-5675",
  },
  {
    name: "Gettysburg Battlefield KOA",
    slug: "gettysburg-battlefield-koa-pa",
    location: "Gettysburg, Pennsylvania",
    state: "Pennsylvania",
    description: "Historic battlefield camping with museum visits.",
    latitude: 39.8009,
    longitude: -77.2364,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(717) 642-5713",
  },
  {
    name: "Presque Isle State Park",
    slug: "presque-isle-state-park-pa",
    location: "Erie, Pennsylvania",
    state: "Pennsylvania",
    description: "Peninsula beach camping on Lake Erie.",
    latitude: 42.1553,
    longitude: -80.1119,
    amenities: ["RESTROOMS", "SHOWERS", "BEACH", "TRAILS", "BOAT_LAUNCH"],
    phone: "(814) 833-7424",
  },
  {
    name: "Pine Creek Gorge - Pennsylvania Grand Canyon",
    slug: "pine-creek-gorge-pa",
    location: "Wellsboro, Pennsylvania",
    state: "Pennsylvania",
    description: "Deep gorge with scenic vistas and rail trail.",
    latitude: 41.6731,
    longitude: -77.4481,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(570) 724-3061",
  },
  {
    name: "Raystown Lake",
    slug: "raystown-lake-pa",
    location: "Hesston, Pennsylvania",
    state: "Pennsylvania",
    description: "Large lake with water sports and mountain biking.",
    latitude: 40.4047,
    longitude: -78.0767,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BOAT_LAUNCH", "BEACH"],
    phone: "(814) 658-3405",
  },

  // VIRGINIA (5 campgrounds)
  {
    name: "Shenandoah National Park - Big Meadows",
    slug: "shenandoah-big-meadows-va",
    location: "Luray, Virginia",
    state: "Virginia",
    description: "Skyline Drive camping with mountain views and wildlife.",
    latitude: 38.5269,
    longitude: -78.4361,
    amenities: ["RESTROOMS", "SHOWERS", "CAMP_STORE", "TRAILS"],
    phone: "(540) 999-3500",
  },
  {
    name: "Virginia Beach KOA",
    slug: "virginia-beach-koa-va",
    location: "Virginia Beach, Virginia",
    state: "Virginia",
    description: "Beach resort camping near oceanfront boardwalk.",
    latitude: 36.8529,
    longitude: -76.0264,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(757) 428-1444",
  },
  {
    name: "First Landing State Park",
    slug: "first-landing-state-park-va",
    location: "Virginia Beach, Virginia",
    state: "Virginia",
    description: "Chesapeake Bay camping where English settlers first landed.",
    latitude: 36.9186,
    longitude: -76.0514,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(757) 412-2300",
  },
  {
    name: "Chincoteague Island KOA",
    slug: "chincoteague-island-koa-va",
    location: "Chincoteague, Virginia",
    state: "Virginia",
    description: "Wild pony island with beach and marsh camping.",
    latitude: 37.9331,
    longitude: -75.3755,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(757) 336-3111",
  },
  {
    name: "Natural Bridge State Park",
    slug: "natural-bridge-state-park-va",
    location: "Natural Bridge, Virginia",
    state: "Virginia",
    description: "Historic natural limestone arch with cave tours.",
    latitude: 37.6300,
    longitude: -79.5433,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(540) 291-1326",
  },

  // NORTH CAROLINA (5 campgrounds)
  {
    name: "Cape Hatteras National Seashore",
    slug: "cape-hatteras-nc",
    location: "Buxton, North Carolina",
    state: "North Carolina",
    description: "Outer Banks beach camping with lighthouse and surfing.",
    latitude: 35.2272,
    longitude: -75.5261,
    amenities: ["RESTROOMS", "SHOWERS", "DUMP_STATION", "BEACH"],
    phone: "(252) 473-2111",
  },
  {
    name: "Blue Ridge Parkway - Mount Pisgah",
    slug: "blue-ridge-parkway-pisgah-nc",
    location: "Waynesville, North Carolina",
    state: "North Carolina",
    description: "Scenic mountain camping along America's favorite drive.",
    latitude: 35.4111,
    longitude: -82.7539,
    amenities: ["RESTROOMS", "FIRE_PITS", "CAMP_STORE", "TRAILS"],
    phone: "(828) 456-9530",
  },
  {
    name: "Hanging Rock State Park",
    slug: "hanging-rock-state-park-nc",
    location: "Danbury, North Carolina",
    state: "North Carolina",
    description: "Mountain park with waterfalls and rock climbing.",
    latitude: 36.3942,
    longitude: -80.2656,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(336) 593-8480",
  },
  {
    name: "Carolina Beach State Park",
    slug: "carolina-beach-state-park-nc",
    location: "Carolina Beach, North Carolina",
    state: "North Carolina",
    description: "Coastal camping with marina and Venus flytraps.",
    latitude: 34.0453,
    longitude: -77.9047,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BOAT_LAUNCH", "TRAILS"],
    phone: "(910) 458-8206",
  },
  {
    name: "Asheville East KOA",
    slug: "asheville-east-koa-nc",
    location: "Swannanoa, North Carolina",
    state: "North Carolina",
    description: "Mountain camping near Blue Ridge Parkway and Biltmore Estate.",
    latitude: 35.5989,
    longitude: -82.3931,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(828) 686-3121",
  },

  // SOUTH CAROLINA (3 campgrounds)
  {
    name: "Huntington Beach State Park",
    slug: "huntington-beach-state-park-sc",
    location: "Murrells Inlet, South Carolina",
    state: "South Carolina",
    description: "Beach camping with Atalaya Castle and salt marsh.",
    latitude: 33.5100,
    longitude: -79.0558,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(843) 237-4440",
  },
  {
    name: "Myrtle Beach State Park",
    slug: "myrtle-beach-state-park-sc",
    location: "Myrtle Beach, South Carolina",
    state: "South Carolina",
    description: "Popular beach camping with fishing pier.",
    latitude: 33.6542,
    longitude: -78.9361,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH"],
    phone: "(843) 238-5325",
  },
  {
    name: "Congaree National Park",
    slug: "congaree-national-park-sc",
    location: "Hopkins, South Carolina",
    state: "South Carolina",
    description: "Old-growth bottomland forest with boardwalk trails.",
    latitude: 33.7947,
    longitude: -80.7819,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(803) 776-4396",
  },

  // GEORGIA (5 campgrounds)
  {
    name: "Cumberland Island National Seashore",
    slug: "cumberland-island-ns-ga",
    location: "St. Marys, Georgia",
    state: "Georgia",
    description: "Wild island camping with wild horses accessible by ferry.",
    latitude: 30.8508,
    longitude: -81.4508,
    amenities: ["RESTROOMS", "BEACH", "TRAILS"],
    phone: "(912) 882-4336",
  },
  {
    name: "Tallulah Gorge State Park",
    slug: "tallulah-gorge-state-park-ga",
    location: "Tallulah Falls, Georgia",
    state: "Georgia",
    description: "Deep gorge with suspension bridge and waterfalls.",
    latitude: 34.7389,
    longitude: -83.3931,
    amenities: ["RESTROOMS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(706) 754-7981",
  },
  {
    name: "Stephen C. Foster State Park",
    slug: "stephen-c-foster-state-park-ga",
    location: "Fargo, Georgia",
    state: "Georgia",
    description: "Okefenokee Swamp wilderness with boat tours.",
    latitude: 30.8142,
    longitude: -82.3561,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BOAT_LAUNCH"],
    phone: "(912) 637-5274",
  },
  {
    name: "Amicalola Falls State Park",
    slug: "amicalola-falls-state-park-ga",
    location: "Dawsonville, Georgia",
    state: "Georgia",
    description: "Tallest waterfall in Georgia with Appalachian Trail access.",
    latitude: 34.5631,
    longitude: -84.2486,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(706) 265-4703",
  },
  {
    name: "Skidaway Island State Park",
    slug: "skidaway-island-state-park-ga",
    location: "Savannah, Georgia",
    state: "Georgia",
    description: "Coastal salt marsh camping near historic Savannah.",
    latitude: 31.9478,
    longitude: -81.0369,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(912) 598-2300",
  },

  // ALABAMA (3 campgrounds)
  {
    name: "Gulf State Park",
    slug: "gulf-state-park-al",
    location: "Gulf Shores, Alabama",
    state: "Alabama",
    description: "White sand beaches with nature center and pier.",
    latitude: 30.2764,
    longitude: -87.6311,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(251) 948-7275",
  },
  {
    name: "Cheaha State Park",
    slug: "cheaha-state-park-al",
    location: "Delta, Alabama",
    state: "Alabama",
    description: "Highest point in Alabama with mountain views.",
    latitude: 33.4864,
    longitude: -85.8092,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(256) 488-5111",
  },
  {
    name: "DeSoto State Park",
    slug: "desoto-state-park-al",
    location: "Fort Payne, Alabama",
    state: "Alabama",
    description: "Waterfalls and mountain streams with hiking trails.",
    latitude: 34.5128,
    longitude: -85.6136,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(256) 845-5380",
  },

  // MISSISSIPPI (2 campgrounds)
  {
    name: "Tishomingo State Park",
    slug: "tishomingo-state-park-ms",
    location: "Tishomingo, Mississippi",
    state: "Mississippi",
    description: "Rock formations with hiking and scenic overlooks.",
    latitude: 34.6367,
    longitude: -88.2128,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(662) 438-6914",
  },
  {
    name: "Gulf Islands National Seashore",
    slug: "gulf-islands-national-seashore-ms",
    location: "Ocean Springs, Mississippi",
    state: "Mississippi",
    description: "Barrier island camping with pristine beaches.",
    latitude: 30.3897,
    longitude: -88.8217,
    amenities: ["RESTROOMS", "BEACH", "TRAILS"],
    phone: "(228) 875-9057",
  },

  // LOUISIANA (3 campgrounds)
  {
    name: "Fontainebleau State Park",
    slug: "fontainebleau-state-park-la",
    location: "Mandeville, Louisiana",
    state: "Louisiana",
    description: "Lake Pontchartrain camping near New Orleans.",
    latitude: 30.3347,
    longitude: -90.0564,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(985) 624-4443",
  },
  {
    name: "Chicot State Park",
    slug: "chicot-state-park-la",
    location: "Ville Platte, Louisiana",
    state: "Louisiana",
    description: "Largest state park with lake and cypress swamp.",
    latitude: 30.8897,
    longitude: -92.1731,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BOAT_LAUNCH", "TRAILS"],
    phone: "(888) 677-2442",
  },
  {
    name: "Bayou Segnette State Park",
    slug: "bayou-segnette-state-park-la",
    location: "Westwego, Louisiana",
    state: "Louisiana",
    description: "Wetlands camping near New Orleans with wave pool.",
    latitude: 29.8858,
    longitude: -90.1881,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "POOL", "BOAT_LAUNCH"],
    phone: "(504) 736-7140",
  },

  // ARKANSAS (3 campgrounds)
  {
    name: "Buffalo National River",
    slug: "buffalo-national-river-ar",
    location: "Harrison, Arkansas",
    state: "Arkansas",
    description: "Free-flowing river with canoeing and bluff camping.",
    latitude: 36.0386,
    longitude: -93.2119,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS", "BOAT_LAUNCH"],
    phone: "(870) 439-2502",
  },
  {
    name: "Devil's Den State Park",
    slug: "devils-den-state-park-ar",
    location: "West Fork, Arkansas",
    state: "Arkansas",
    description: "Ozark mountains with caves and waterfalls.",
    latitude: 35.7858,
    longitude: -94.2369,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(479) 761-3325",
  },
  {
    name: "Petit Jean State Park",
    slug: "petit-jean-state-park-ar",
    location: "Morrilton, Arkansas",
    state: "Arkansas",
    description: "Cedar Falls and Rock House Cave with scenic overlooks.",
    latitude: 35.1297,
    longitude: -92.9014,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(501) 727-5441",
  },

  // TENNESSEE (5 campgrounds)
  {
    name: "Great Smoky Mountains - Elkmont",
    slug: "great-smoky-mountains-elkmont-tn",
    location: "Gatlinburg, Tennessee",
    state: "Tennessee",
    description: "Historic camp with old-growth forest and streams.",
    latitude: 35.6586,
    longitude: -83.5831,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(865) 436-1200",
  },
  {
    name: "Fall Creek Falls State Park",
    slug: "fall-creek-falls-state-park-tn",
    location: "Spencer, Tennessee",
    state: "Tennessee",
    description: "256-foot waterfall with gorge camping.",
    latitude: 35.6603,
    longitude: -85.3350,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(423) 881-5298",
  },
  {
    name: "Pigeon Forge KOA",
    slug: "pigeon-forge-koa-tn",
    location: "Pigeon Forge, Tennessee",
    state: "Tennessee",
    description: "Gateway to Smokies near Dollywood theme park.",
    latitude: 35.7881,
    longitude: -83.5539,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(865) 453-7903",
  },
  {
    name: "Burgess Falls State Park",
    slug: "burgess-falls-state-park-tn",
    location: "Sparta, Tennessee",
    state: "Tennessee",
    description: "Waterfall cascade with scenic hiking trail.",
    latitude: 36.0864,
    longitude: -85.6097,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(931) 432-5312",
  },
  {
    name: "Roan Mountain State Park",
    slug: "roan-mountain-state-park-tn",
    location: "Roan Mountain, Tennessee",
    state: "Tennessee",
    description: "Appalachian Trail access with rhododendron gardens.",
    latitude: 36.1792,
    longitude: -82.1031,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(423) 772-0190",
  },

  
// KENTUCKY (3 campgrounds)
  {
    name: "Mammoth Cave National Park",
    slug: "mammoth-cave-np-ky",
    location: "Mammoth Cave, Kentucky",
    state: "Kentucky",
    description: "World's longest cave system with underground tours.",
    latitude: 37.1862,
    longitude: -86.1003,
    amenities: ["RESTROOMS", "SHOWERS", "FIRE_PITS", "TRAILS"],
    phone: "(270) 758-2180",
  },
  {
    name: "Natural Bridge State Resort Park",
    slug: "natural-bridge-state-resort-park-ky",
    location: "Slade, Kentucky",
    state: "Kentucky",
    description: "Sandstone arch with sky lift and hiking trails.",
    latitude: 37.7775,
    longitude: -83.6819,
    amenies: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(606) 663-2214",
  },
  {
    name: "Cumberland Falls State Resort Park",
    slug: "cumberland-falls-state-resort-park-ky",
    location: "Corbin, Kentucky",
    state: "Kentucky",
    description: "Moonbow waterfall with whitewater rafting.",
    latitude: 36.8389,
    longitude: -84.3431,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(606) 528-4121",
  },

  // WEST VIRGINIA (3 campgrounds)
  {
    name: "New River Gorge National Park",
    slug: "new-river-gorge-np-wv",
    location: "Fayetteville, West Virginia",
    state: "West Virginia",
    description: "Whitewater rafting and iconic bridge with gorge camping.",
    latitude: 37.9739,
    longitude: -81.0722,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(304) 465-0508",
  },
  {
    name: "Seneca Rocks Discovery Center",
    slug: "seneca-rocks-wv",
    location: "Seneca Rocks, West Virginia",
    state: "West Virginia",
    description: "Rock climbing mecca with spectacular formations.",
    latitude: 38.8344,
    longitude: -79.3772,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(304) 567-2827",
  },
  {
    name: "Blackwater Falls State Park",
    slug: "blackwater-falls-state-park-wv",
    location: "Davis, West Virginia",
    state: "West Virginia",
    description: "Amber-colored waterfall with mountain biking.",
    latitude: 39.1131,
    longitude: -79.4869,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(304) 259-5216",
  },

  // OHIO (3 campgrounds)
  {
    name: "Hocking Hills State Park",
    slug: "hocking-hills-state-park-oh",
    location: "Logan, Ohio",
    state: "Ohio",
    description: "Rock formations, caves, and waterfalls in forest setting.",
    latitude: 39.4394,
    longitude: -82.5381,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(740) 385-6841",
  },
  {
    name: "Cuyahoga Valley National Park",
    slug: "cuyahoga-valley-np-oh",
    location: "Brecksville, Ohio",
    state: "Ohio",
    description: "Waterfalls and canal towpath between Cleveland and Akron.",
    latitude: 41.2808,
    longitude: -81.5678,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(330) 657-2752",
  },
  {
    name: "East Harbor State Park",
    slug: "east-harbor-state-park-oh",
    location: "Marblehead, Ohio",
    state: "Ohio",
    description: "Lake Erie camping with beach and Cedar Point nearby.",
    latitude: 41.5456,
    longitude: -82.7842,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "BOAT_LAUNCH"],
    phone: "(419) 734-4424",
  },

  // INDIANA (3 campgrounds)
  {
    name: "Indiana Dunes National Park",
    slug: "indiana-dunes-np-in",
    location: "Porter, Indiana",
    state: "Indiana",
    description: "Lake Michigan dunes near Chicago with beach camping.",
    latitude: 41.6533,
    longitude: -87.0525,
    amenities: ["RESTROOMS", "BEACH", "TRAILS"],
    phone: "(219) 395-1882",
  },
  {
    name: "Turkey Run State Park",
    slug: "turkey-run-state-park-in",
    location: "Marshall, Indiana",
    state: "Indiana",
    description: "Sandstone gorges with suspension bridge and canoeing.",
    latitude: 39.9056,
    longitude: -87.2206,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(765) 597-2635",
  },
  {
    name: "Clifty Falls State Park",
    slug: "clifty-falls-state-park-in",
    location: "Madison, Indiana",
    state: "Indiana",
    description: "Waterfalls and rugged canyon trails along Ohio River.",
    latitude: 38.7856,
    longitude: -85.4400,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(812) 273-8885",
  },

  // ILLINOIS (3 campgrounds)
  {
    name: "Starved Rock State Park",
    slug: "starved-rock-state-park-il",
    location: "Oglesby, Illinois",
    state: "Illinois",
    description: "18 canyons with waterfalls along Illinois River.",
    latitude: 41.3197,
    longitude: -88.9939,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(815) 667-4726",
  },
  {
    name: "Garden of the Gods - Shawnee National Forest",
    slug: "garden-of-the-gods-il",
    location: "Herod, Illinois",
    state: "Illinois",
    description: "Scenic rock formations with panoramic views.",
    latitude: 37.6150,
    longitude: -88.3867,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(618) 658-2111",
  },
  {
    name: "Mississippi Palisades State Park",
    slug: "mississippi-palisades-state-park-il",
    location: "Savanna, Illinois",
    state: "Illinois",
    description: "River bluffs with rock climbing and bald eagle viewing.",
    latitude: 42.0947,
    longitude: -90.1761,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(815) 273-2731",
  },

  // MISSOURI (3 campgrounds)
  {
    name: "Ha Ha Tonka State Park",
    slug: "ha-ha-tonka-state-park-mo",
    location: "Camdenton, Missouri",
    state: "Missouri",
    description: "Castle ruins with karst landscape and springs.",
    latitude: 37.9842,
    longitude: -92.7603,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(573) 346-2986",
  },
  {
    name: "Lake of the Ozarks State Park",
    slug: "lake-of-the-ozarks-state-park-mo",
    location: "Kaiser, Missouri",
    state: "Missouri",
    description: "Largest state park with lake recreation.",
    latitude: 38.1397,
    longitude: -92.5981,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "BOAT_LAUNCH"],
    phone: "(573) 348-2694",
  },
  {
    name: "Elephant Rocks State Park",
    slug: "elephant-rocks-state-park-mo",
    location: "Belleview, Missouri",
    state: "Missouri",
    description: "Giant granite boulders with Braille trail.",
    latitude: 37.6711,
    longitude: -90.6236,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(573) 546-3454",
  },

  // IOWA (3 campgrounds)
  {
    name: "Ledges State Park",
    slug: "ledges-state-park-ia",
    location: "Madrid, Iowa",
    state: "Iowa",
    description: "Sandstone cliffs with scenic Des Moines River valley.",
    latitude: 42.0272,
    longitude: -93.9028,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(515) 432-1852",
  },
  {
    name: "Backbone State Park",
    slug: "backbone-state-park-ia",
    location: "Strawberry Point, Iowa",
    state: "Iowa",
    description: "Iowa's first state park with rock formations and lake.",
    latitude: 42.6236,
    longitude: -91.4806,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(563) 924-2527",
  },
  {
    name: "Pikes Peak State Park",
    slug: "pikes-peak-state-park-ia",
    location: "McGregor, Iowa",
    state: "Iowa",
    description: "Bluff overlooks of Mississippi River with effigy mounds.",
    latitude: 43.0847,
    longitude: -91.1519,
    amenities: ["RESTROOMS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(563) 873-2341",
  },

  // KANSAS (2 campgrounds)
  {
    name: "Kanopolis State Park",
    slug: "kanopolis-state-park-ks",
    location: "Marquette, Kansas",
    state: "Kansas",
    description: "Lake and prairie camping with rock formations.",
    latitude: 38.7097,
    longitude: -98.1556,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "BOAT_LAUNCH"],
    phone: "(785) 546-2565",
  },
  {
    name: "Tallgrass Prairie National Preserve",
    slug: "tallgrass-prairie-national-preserve-ks",
    location: "Strong City, Kansas",
    state: "Kansas",
    description: "Rare tallgrass prairie ecosystem with bison herd.",
    latitude: 38.4403,
    longitude: -96.8353,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(620) 273-8494",
  },

  // NEBRASKA (2 campgrounds)
  {
    name: "Scotts Bluff National Monument",
    slug: "scotts-bluff-national-monument-ne",
    location: "Gering, Nebraska",
    state: "Nebraska",
    description: "Oregon Trail landmark with bluff views.",
    latitude: 41.8342,
    longitude: -103.7008,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(308) 436-9700",
  },
  {
    name: "Niobrara State Park",
    slug: "niobrara-state-park-ne",
    location: "Niobrara, Nebraska",
    state: "Nebraska",
    description: "River confluence camping with cabins and trails.",
    latitude: 42.7858,
    longitude: -98.0292,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(402) 857-3373",
  },

  // OKLAHOMA (2 campgrounds)
  {
    name: "Beavers Bend State Park",
    slug: "beavers-bend-state-park-ok",
    location: "Broken Bow, Oklahoma",
    state: "Oklahoma",
    description: "Mountain Fork River with trout fishing and pine forests.",
    latitude: 34.1353,
    longitude: -94.6967,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS", "BOAT_LAUNCH"],
    phone: "(580) 494-6300",
  },
  {
    name: "Robbers Cave State Park",
    slug: "robbers-cave-state-park-ok",
    location: "Wilburton, Oklahoma",
    state: "Oklahoma",
    description: "Outlaw hideout caves with rock climbing and horseback riding.",
    latitude: 34.9286,
    longitude: -95.3189,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(918) 465-2565",
  },

  // IDAHO (5 campgrounds)
  {
    name: "Craters of the Moon National Monument",
    slug: "craters-of-the-moon-id",
    location: "Arco, Idaho",
    state: "Idaho",
    description: "Volcanic landscape with lava tube caves.",
    latitude: 43.4162,
    longitude: -113.5161,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(208) 527-1300",
  },
  {
    name: "Redfish Lake - Sawtooth National Forest",
    slug: "redfish-lake-id",
    location: "Stanley, Idaho",
    state: "Idaho",
    description: "Alpine lake camping with mountain views and salmon spawning.",
    latitude: 44.1514,
    longitude: -114.9147,
    amenities: ["RESTROOMS", "SHOWERS", "FIRE_PITS", "BOAT_LAUNCH", "TRAILS"],
    phone: "(208) 774-3000",
  },
  {
    name: "Bruneau Dunes State Park",
    slug: "bruneau-dunes-state-park-id",
    location: "Mountain Home, Idaho",
    state: "Idaho",
    description: "Tallest single-structured sand dune in North America.",
    latitude: 42.8917,
    longitude: -115.7208,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(208) 366-7919",
  },
  {
    name: "City of Rocks National Reserve",
    slug: "city-of-rocks-id",
    location: "Almo, Idaho",
    state: "Idaho",
    description: "Granite spires with rock climbing and California Trail history.",
    latitude: 42.0686,
    longitude: -113.7122,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(208) 824-5519",
  },
  {
    name: "Priest Lake State Park",
    slug: "priest-lake-state-park-id",
    location: "Coolin, Idaho",
    state: "Idaho",
    description: "Pristine mountain lake with old-growth cedar forests.",
    latitude: 48.5578,
    longitude: -116.8831,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "BOAT_LAUNCH"],
    phone: "(208) 443-6710",
  },

  // NEVADA (5 campgrounds)
  {
    name: "Valley of Fire State Park",
    slug: "valley-of-fire-state-park-nv",
    location: "Overton, Nevada",
    state: "Nevada",
    description: "Red sandstone formations with ancient petroglyphs.",
    latitude: 36.4819,
    longitude: -114.5264,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(702) 397-2088",
  },
  {
    name: "Great Basin National Park",
    slug: "great-basin-np-nv",
    location: "Baker, Nevada",
    state: "Nevada",
    description: "Ancient bristlecone pines and Lehman Caves.",
    latitude: 38.9833,
    longitude: -114.3000,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(775) 234-7331",
  },
  {
    name: "Lake Mead National Recreation Area",
    slug: "lake-mead-nra-nv",
    location: "Boulder City, Nevada",
    state: "Nevada",
    description: "Desert lake camping with Hoover Dam views.",
    latitude: 36.1089,
    longitude: -114.3869,
    amenities: ["RESTROOMS", "DUMP_STATION", "BOAT_LAUNCH", "BEACH"],
    phone: "(702) 293-8990",
  },
  {
    name: "Cathedral Gorge State Park",
    slug: "cathedral-gorge-state-park-nv",
    location: "Panaca, Nevada",
    state: "Nevada",
    description: "Dramatic erosional features with slot canyons.",
    latitude: 37.7969,
    longitude: -114.4186,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(775) 728-4460",
  },
  {
    name: "Las Vegas KOA at Sam's Town",
    slug: "las-vegas-koa-nv",
    location: "Las Vegas, Nevada",
    state: "Nevada",
    description: "Urban camping near casinos and entertainment.",
    latitude: 36.1147,
    longitude: -115.0622,
    amenities: ["WIFI", "POOL", "SHOWERS", "RESTROOMS", "ELECTRIC_HOOKUPS", "WATER", "DUMP_STATION"],
    phone: "(702) 451-5527",
  },

  // NEW MEXICO (5 campgrounds)
  {
    name: "White Sands National Park",
    slug: "white-sands-np-nm",
    location: "Alamogordo, New Mexico",
    state: "New Mexico",
    description: "Gypsum sand dunes with sledding and hiking.",
    latitude: 32.7872,
    longitude: -106.3256,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(575) 479-6124",
  },
  {
    name: "Carlsbad Caverns National Park",
    slug: "carlsbad-caverns-np-nm",
    location: "Carlsbad, New Mexico",
    state: "New Mexico",
    description: "Massive cave system with bat flight program.",
    latitude: 32.1479,
    longitude: -104.5567,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(575) 785-2232",
  },
  {
    name: "Bandelier National Monument",
    slug: "bandelier-national-monument-nm",
    location: "Los Alamos, New Mexico",
    state: "New Mexico",
    description: "Ancestral Pueblo dwellings carved in volcanic rock.",
    latitude: 35.7781,
    longitude: -106.2711,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(505) 672-3861",
  },
  {
    name: "Elephant Butte Lake State Park",
    slug: "elephant-butte-lake-state-park-nm",
    location: "Elephant Butte, New Mexico",
    state: "New Mexico",
    description: "Largest lake in New Mexico with water sports.",
    latitude: 33.1528,
    longitude: -107.1928,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BOAT_LAUNCH", "BEACH"],
    phone: "(575) 744-5421",
  },
  {
    name: "City of Rocks State Park",
    slug: "city-of-rocks-state-park-nm",
    location: "Faywood, New Mexico",
    state: "New Mexico",
    description: "Volcanic rock formations with stargazing.",
    latitude: 32.5758,
    longitude: -108.0142,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "TRAILS"],
    phone: "(575) 536-2800",
  },

  // ALASKA (5 campgrounds)
  {
    name: "Denali National Park - Wonder Lake",
    slug: "denali-wonder-lake-ak",
    location: "Denali Park, Alaska",
    state: "Alaska",
    description: "Remote tundra camping with Mount Denali views.",
    latitude: 63.4661,
    longitude: -150.8581,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(907) 683-9532",
  },
  {
    name: "Kenai Fjords National Park",
    slug: "kenai-fjords-np-ak",
    location: "Seward, Alaska",
    state: "Alaska",
    description: "Coastal glacier camping with wildlife viewing.",
    latitude: 59.9181,
    longitude: -149.6511,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(907) 422-0500",
  },
  {
    name: "Chugach State Park",
    slug: "chugach-state-park-ak",
    location: "Anchorage, Alaska",
    state: "Alaska",
    description: "Third-largest state park in US with mountains and glaciers.",
    latitude: 61.2353,
    longitude: -149.4408,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(907) 345-5014",
  },
  {
    name: "Chilkat State Park",
    slug: "chilkat-state-park-ak",
    location: "Haines, Alaska",
    state: "Alaska",
    description: "Coastal rainforest with bald eagle viewing.",
    latitude: 59.1586,
    longitude: -135.4497,
    amenities: ["RESTROOMS", "BEACH", "TRAILS"],
    phone: "(907) 766-2292",
  },
  {
    name: "Homer Spit Campground",
    slug: "homer-spit-campground-ak",
    location: "Homer, Alaska",
    state: "Alaska",
    description: "Waterfront camping on famous spit with halibut fishing.",
    latitude: 59.4394,
    longitude: -151.4211,
    amenities: ["RESTROOMS", "DUMP_STATION", "BEACH"],
    phone: "(907) 235-8206",
  },

  // HAWAII (5 campgrounds)
  {
    name: "Volcanoes National Park - Namakanipaio",
    slug: "volcanoes-np-namakanipaio-hi",
    location: "Hawaii Volcanoes National Park, Hawaii",
    state: "Hawaii",
    description: "Active volcano camping with lava viewing.",
    latitude: 19.4194,
    longitude: -155.2872,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(808) 985-6178",
  },
  {
    name: "Haleakalā National Park",
    slug: "haleakala-np-hi",
    location: "Kula, Hawaii",
    state: "Hawaii",
    description: "Summit crater camping with sunrise viewing.",
    latitude: 20.7097,
    longitude: -156.2533,
    amenities: ["RESTROOMS", "TRAILS"],
    phone: "(808) 572-4400",
  },
  {
    name: "Koke'e State Park",
    slug: "kokee-state-park-hi",
    location: "Kauai, Hawaii",
    state: "Hawaii",
    description: "Mountain forest camping with Waimea Canyon views.",
    latitude: 22.1219,
    longitude: -159.6619,
    amenities: ["RESTROOMS", "SHOWERS", "TRAILS"],
    phone: "(808) 274-3444",
  },
  {
    name: "Malaekahana State Recreation Area",
    slug: "malaekahana-state-recreation-area-hi",
    location: "Oahu, Hawaii",
    state: "Hawaii",
    description: "Beach camping with coral reefs and tidepools.",
    latitude: 21.6611,
    longitude: -157.9294,
    amenities: ["RESTROOMS", "SHOWERS", "BEACH"],
    phone: "(808) 293-1736",
  },
  {
    name: "Wai'anapanapa State Park",
    slug: "waianapanapa-state-park-hi",
    location: "Maui, Hawaii",
    state: "Hawaii",
    description: "Black sand beach with lava tube caves.",
    latitude: 20.7886,
    longitude: -156.0039,
    amenities: ["RESTROOMS", "BEACH", "TRAILS"],
    phone: "(808) 984-8109",
  },

  // VERMONT (3 campgrounds)
  {
    name: "Green Mountain National Forest",
    slug: "green-mountain-national-forest-vt",
    location: "Rutland, Vermont",
    state: "Vermont",
    description: "Mountain forest camping with Long Trail access.",
    latitude: 43.2428,
    longitude: -72.8403,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(802) 747-6700",
  },
  {
    name: "Burton Island State Park",
    slug: "burton-island-state-park-vt",
    location: "St. Albans, Vermont",
    state: "Vermont",
    description: "Island camping on Lake Champlain accessible by boat.",
    latitude: 44.8197,
    longitude: -73.2878,
    amenities: ["RESTROOMS", "SHOWERS", "BEACH", "BOAT_LAUNCH"],
    phone: "(802) 524-6353",
  },
  {
    name: "Smugglers' Notch State Park",
    slug: "smugglers-notch-state-park-vt",
    location: "Stowe, Vermont",
    state: "Vermont",
    description: "Mountain pass camping near skiing and hiking.",
    latitude: 44.5889,
    longitude: -72.7878,
    amenities: ["RESTROOMS", "SHOWERS", "FIRE_PITS", "TRAILS"],
    phone: "(802) 253-4014",
  },

  // NEW HAMPSHIRE (3 campgrounds)
  {
    name: "White Mountain National Forest",
    slug: "white-mountain-national-forest-nh",
    location: "Lincoln, New Hampshire",
    state: "New Hampshire",
    description: "Presidential Range camping with mountain hiking.",
    latitude: 44.0581,
    longitude: -71.5689,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(603) 536-6100",
  },
  {
    name: "Franconia Notch State Park",
    slug: "franconia-notch-state-park-nh",
    location: "Franconia, New Hampshire",
    state: "New Hampshire",
    description: "Scenic notch with Flume Gorge and aerial tramway.",
    latitude: 44.1539,
    longitude: -71.6886,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(603) 745-8391",
  },
  {
    name: "Crawford Notch State Park",
    slug: "crawford-notch-state-park-nh",
    location: "Bartlett, New Hampshire",
    state: "New Hampshire",
    description: "Mountain notch with waterfalls and historical sites.",
    latitude: 44.2189,
    longitude: -71.4078,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(603) 374-2272",
  },

  // CONNECTICUT (2 campgrounds)
  {
    name: "Hammonasset Beach State Park",
    slug: "hammonasset-beach-state-park-ct",
    location: "Madison, Connecticut",
    state: "Connecticut",
    description: "Largest beach campground with Long Island Sound access.",
    latitude: 41.2653,
    longitude: -72.5586,
    amenities: ["RESTROOMS", "SHOWERS", "DUMP_STATION", "BEACH"],
    phone: "(203) 245-2785",
  },
  {
    name: "Macedonia Brook State Park",
    slug: "macedonia-brook-state-park-ct",
    location: "Kent, Connecticut",
    state: "Connecticut",
    description: "Mountain hiking with Appalachian Trail access.",
    latitude: 41.6728,
    longitude: -73.4617,
    amenities: ["RESTROOMS", "FIRE_PITS", "TRAILS"],
    phone: "(860) 927-3238",
  },

  // RHODE ISLAND (2 campgrounds)
  {
    name: "Fishermen's Memorial State Park",
    slug: "fishermens-memorial-state-park-ri",
    location: "Narragansett, Rhode Island",
    state: "Rhode Island",
    description: "Coastal camping with saltwater fishing.",
    latitude: 41.4139,
    longitude: -71.4728,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "DUMP_STATION"],
    phone: "(401) 789-8374",
  },
  {
    name: "Burlingame State Park",
    slug: "burlingame-state-park-ri",
    location: "Charlestown, Rhode Island",
    state: "Rhode Island",
    description: "Forest camping near beaches with swimming pond.",
    latitude: 41.3839,
    longitude: -71.6478,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH"],
    phone: "(401) 322-7337",
  },

  // MASSACHUSETTS (3 campgrounds)
  {
    name: "Cape Cod National Seashore",
    slug: "cape-cod-national-seashore-ma",
    location: "Wellfleet, Massachusetts",
    state: "Massachusetts",
    description: "Coastal dune camping with ocean beaches.",
    latitude: 41.8972,
    longitude: -70.0453,
    amenities: ["RESTROOMS", "SHOWERS", "BEACH", "TRAILS"],
    phone: "(508) 771-2144",
  },
  {
    name: "Mohawk Trail State Forest",
    slug: "mohawk-trail-state-forest-ma",
    location: "Charlemont, Massachusetts",
    state: "Massachusetts",
    description: "Old-growth forest along scenic mountain highway.",
    latitude: 42.6331,
    longitude: -72.9208,
    amenities: ["RESTROOMS", "SHOWERS", "FIRE_PITS", "TRAILS"],
    phone: "(413) 339-5504",
  },
  {
    name: "Nickerson State Park",
    slug: "nickerson-state-park-ma",
    location: "Brewster, Massachusetts",
    state: "Massachusetts",
    description: "Cape Cod kettle pond camping with biking trails.",
    latitude: 41.7617,
    longitude: -70.0211,
    amenities: ["RESTROOMS", "SHOWERS", "FIRE_PITS", "BEACH", "TRAILS"],
    phone: "(508) 896-3491",
  },

  // DELAWARE (2 campgrounds)
  {
    name: "Delaware Seashore State Park",
    slug: "delaware-seashore-state-park-de",
    location: "Rehoboth Beach, Delaware",
    state: "Delaware",
    description: "Atlantic Ocean and bay camping with water sports.",
    latitude: 38.6472,
    longitude: -75.0689,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH"],
    phone: "(302) 227-2800",
  },
  {
    name: "Cape Henlopen State Park",
    slug: "cape-henlopen-state-park-de",
    location: "Lewes, Delaware",
    state: "Delaware",
    description: "Historic fort with dunes and fishing pier.",
    latitude: 38.7992,
    longitude: -75.0906,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(302) 645-8983",
  },

  // MARYLAND (3 campgrounds)
  {
    name: "Assateague Island National Seashore",
    slug: "assateague-island-national-seashore-md",
    location: "Berlin, Maryland",
    state: "Maryland",
    description: "Wild pony island with ocean and bay camping.",
    latitude: 38.2208,
    longitude: -75.1492,
    amenities: ["RESTROOMS", "SHOWERS", "BEACH"],
    phone: "(410) 641-1441",
  },
  {
    name: "Deep Creek Lake State Park",
    slug: "deep-creek-lake-state-park-md",
    location: "Swanton, Maryland",
    state: "Maryland",
    description: "Mountain lake camping with water sports.",
    latitude: 39.5211,
    longitude: -79.3389,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "BOAT_LAUNCH"],
    phone: "(301) 387-5563",
  },
  {
    name: "Greenbrier State Park",
    slug: "greenbrier-state-park-md",
    location: "Boonsboro, Maryland",
    state: "Maryland",
    description: "Appalachian Trail camping with swimming lake.",
    latitude: 39.5872,
    longitude: -77.6239,
    amenities: ["RESTROOMS", "SHOWERS", "ELECTRIC_HOOKUPS", "BEACH", "TRAILS"],
    phone: "(301) 791-4767",
  },

  // NEW JERSEY (3 campgrounds)
  {
    name: "Island Beach State Park",
    slug: "island-beach-state-park-nj",
    location: "Seaside Park, New Jersey",
    state: "New Jersey",
    description: "Barrier island with pristine beaches and dunes.",
    latitude: 39.8408,
    longitude: -74.0931,
    amenities: ["RESTROOMS", "BEACH", "TRAILS"],
    phone: "(732) 793-0506",
  },
  {
    name: "Worthington State Forest",
    slug: "worthington-state-forest-nj",
    location: "Columbia, New Jersey",
    state: "New Jersey",
    description: "Delaware Water Gap camping with Appalachian Trail.",
    latitude: 40.9772,
    longitude: -75.0869,
    amenities: ["RESTROOMS", "SHOWERS", "FIRE_PITS", "TRAILS"],
    phone: "(908) 841-9575",
  },
  {
    name: "Bass River State Forest",
    slug: "bass-river-state-forest-nj",
    location: "New Gretna, New Jersey",
    state: "New Jersey",
    description: "Pine Barrens camping with lake swimming.",
    latitude: 39.6419,
    longitude: -74.4419,
    amenities: ["RESTROOMS", "SHOWERS", "FIRE_PITS", "BEACH", "TRAILS"],
    phone: "(609) 296-1114",
  },
];

async function main() {
  console.log('🏕️  Starting Expanded Campground Seed');
  console.log(`📍 Adding ${campgrounds.length} campgrounds...\n`);

  let imported = 0;
  let skipped = 0;

  for (const campground of campgrounds) {
    try {
      const existing = await prisma.campground.findUnique({
        where: { slug: campground.slug },
      });

      if (existing) {
        console.log(`⏭️  Skipping: ${campground.name} (already exists)`);
        skipped++;
        continue;
      }

      await prisma.campground.create({
        data: campground,
      });

      console.log(`✅ Imported: ${campground.name} - ${campground.location}`);
      imported++;
    } catch (error: any) {
      console.error(`❌ Error importing ${campground.name}:`, error.message);
      continue;
    }
  }

  console.log('\n✅ Seed Complete!');
  console.log(`📊 Stats:`);
  console.log(`   - Successfully imported: ${imported}`);
  console.log(`   - Skipped: ${skipped}`);
  console.log(`\n🎉 Your database now has ${imported + skipped} campgrounds!`);

  await prisma.$disconnect();
}

main().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
