import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface RVPark {
  name: string; location: string; city: string; state: string; zipCode: string;
  description: string; latitude: number; longitude: number;
  imageUrl?: string; websiteUrl?: string; bookingUrl?: string;
  hasElectricHookup?: boolean; hasWaterHookup?: boolean; hasSewerHookup?: boolean;
  hasFullHookups?: boolean; hasPullThrough?: boolean; hasBackIn?: boolean;
  hasRestrooms?: boolean; hasShowers?: boolean; hasLaundry?: boolean;
  hasPool?: boolean; hasDumpStation?: boolean; hasCableTV?: boolean;
  hasPropane?: boolean; hasWifi?: boolean; amenities?: string[];
}

const TOP_50_RV_PARKS: RVPark[] = [
  // ─── ICONIC RESORT / DESTINATION ───────────────────────────────────────
  {
    name: "Disney Fort Wilderness Resort & Campground",
    location: "4510 N Fort Wilderness Trail, Orlando, Florida",
    city: "Orlando", state: "FL", zipCode: "32836",
    description: "The ultimate family camping experience inside Walt Disney World. Full hookups, Disney transportation, two pools, horse trails, and nightly campfire programs with Chip and Dale.",
    latitude: 28.4145, longitude: -81.5731,
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800",
    websiteUrl: "https://disneyworld.disney.go.com/resorts/fort-wilderness-resort-and-campground/",
    bookingUrl: "https://disneyworld.disney.go.com/resorts/fort-wilderness-resort-and-campground/",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true,
    amenities: ["Full Hookups", "Pool", "WiFi", "Disney Transportation", "Horse Trails", "Camp Store", "Petting Farm", "Bike Rentals"],
  },
  {
    name: "Zion Canyon Campground",
    location: "479 Zion Park Blvd, Springdale, Utah",
    city: "Springdale", state: "UT", zipCode: "84767",
    description: "The closest campground to Zion National Park entrance. Walk to the shuttle, surrounded by towering red rock canyon walls. Full hookups and tent sites with breathtaking views.",
    latitude: 37.1986, longitude: -112.9878,
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
    websiteUrl: "https://www.zioncamp.com",
    bookingUrl: "https://www.zioncamp.com/reservations",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasWifi: true, hasDumpStation: true,
    amenities: ["Full Hookups", "WiFi", "Laundry", "Zion Shuttle Access", "Camp Store"],
  },
  {
    name: "Yogi Bear Jellystone Park Camp-Resort at Mammoth Cave",
    location: "1002 Mammoth Cave Rd, Cave City, Kentucky",
    city: "Cave City", state: "KY", zipCode: "42127",
    description: "Family resort near Mammoth Cave National Park with waterpark, mini golf, and Yogi Bear character meet and greets. One of the most popular family RV destinations in the country.",
    latitude: 37.1337, longitude: -86.0819,
    imageUrl: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800",
    websiteUrl: "https://www.jellystonecavecity.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true, hasCableTV: true,
    amenities: ["Waterpark", "Mini Golf", "Jumping Pillow", "Character Experiences", "Planned Activities"],
  },
  {
    name: "Myrtle Beach Travel Park",
    location: "10108 Kings Rd, Myrtle Beach, South Carolina",
    city: "Myrtle Beach", state: "SC", zipCode: "29572",
    description: "Premier oceanfront RV resort on the Grand Strand. Direct beach access, multiple pools, live entertainment, and the full Myrtle Beach experience steps from your site.",
    latitude: 33.7901, longitude: -78.7264,
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    websiteUrl: "https://www.myrtlebeachtravelpark.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true, hasCableTV: true,
    amenities: ["Oceanfront", "Beach Access", "Pool", "Entertainment", "Camp Store"],
  },
  {
    name: "Thousand Trails Seaside",
    location: "1250 Pacific Ave, Seaside, Oregon",
    city: "Seaside", state: "OR", zipCode: "97138",
    description: "Pacific Northwest coastal RV resort steps from the famous Seaside Promenade. Beach access, full hookups, and easy access to Cannon Beach and Haystack Rock.",
    latitude: 45.9935, longitude: -123.9222,
    imageUrl: "https://images.unsplash.com/photo-1511576661531-b34d7da5d0bb?w=800",
    websiteUrl: "https://www.thousandtrails.com/rv-parks/seaside",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasDumpStation: true,
    amenities: ["Beach Access", "Pool", "Hot Tub", "Game Room", "Planned Activities"],
  },
  {
    name: "KOA Nashville",
    location: "2626 Music Valley Dr, Nashville, Tennessee",
    city: "Nashville", state: "TN", zipCode: "37214",
    description: "The top-rated KOA in Tennessee, steps from the Grand Ole Opry and Opryland. Full hookups, cabins, pool, and live music nearby every night.",
    latitude: 36.2081, longitude: -86.6934,
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800",
    websiteUrl: "https://koa.com/campgrounds/nashville",
    bookingUrl: "https://koa.com/campgrounds/nashville/reserve/",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true,
    amenities: ["Pool", "WiFi", "Pancake Breakfast", "Cabins", "Near Grand Ole Opry"],
  },
  {
    name: "Hilton Head Harbor RV Resort & Marina",
    location: "43 Jenkins Rd, Hilton Head Island, South Carolina",
    city: "Hilton Head Island", state: "SC", zipCode: "29926",
    description: "Luxury RV resort on Hilton Head Island with marina access, pool, tennis, and easy access to world-class beaches and golf courses.",
    latitude: 32.2163, longitude: -80.7526,
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    websiteUrl: "https://www.hiltonheadharbor.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasPullThrough: true, hasDumpStation: true,
    amenities: ["Marina", "Pool", "Tennis", "Fitness Center", "Fishing", "Near Beach"],
  },
  {
    name: "Bar Harbor Campground",
    location: "409 ME-3, Bar Harbor, Maine",
    city: "Bar Harbor", state: "ME", zipCode: "04609",
    description: "Premier campground near Acadia National Park. Full hookups, wooded sites, and minutes from Bar Harbor village and the famous carriage roads of Acadia.",
    latitude: 44.3876, longitude: -68.2733,
    imageUrl: "https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=800",
    websiteUrl: "https://www.barharborcampground.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasWifi: true,
    hasDumpStation: true, hasPullThrough: true,
    amenities: ["Full Hookups", "WiFi", "Laundry", "Near Acadia NP", "Shuttle to Bar Harbor"],
  },
  {
    name: "Glacier Campground",
    location: "12070 US-2, West Glacier, Montana",
    city: "West Glacier", state: "MT", zipCode: "59936",
    description: "The closest private campground to Glacier National Park west entrance. Full hookups and tent sites surrounded by stunning Rocky Mountain scenery.",
    latitude: 48.4969, longitude: -113.9811,
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    websiteUrl: "https://www.glaciercampground.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasWifi: true,
    hasDumpStation: true,
    amenities: ["Full Hookups", "WiFi", "Laundry", "Near Glacier NP", "Fishing"],
  },
  {
    name: "Yellowstone Grizzly RV Park",
    location: "210 S Electric St, West Yellowstone, Montana",
    city: "West Yellowstone", state: "MT", zipCode: "59758",
    description: "Top-rated RV park in West Yellowstone, the west gateway to Yellowstone National Park. Full hookups, heated pool, and steps from restaurants and shops.",
    latitude: 44.6605, longitude: -111.1013,
    imageUrl: "https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800",
    websiteUrl: "https://yellowstonegrizzlyrv.com",
    bookingUrl: "https://yellowstonegrizzlyrv.com/reservations",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasPullThrough: true, hasDumpStation: true,
    amenities: ["Heated Pool", "Full Hookups", "WiFi", "Laundry", "Near Yellowstone NP"],
  },
  {
    name: "Grand Canyon Trailer Village RV Park",
    location: "Village Loop Dr, Grand Canyon Village, Arizona",
    city: "Grand Canyon Village", state: "AZ", zipCode: "86023",
    description: "The only RV park inside Grand Canyon National Park on the South Rim. Full hookups with direct access to canyon viewpoints and hiking trails.",
    latitude: 36.0544, longitude: -112.1401,
    imageUrl: "https://images.unsplash.com/photo-1615839623754-2f9295f44de4?w=800",
    websiteUrl: "https://www.visitgrandcanyon.com/trailer-village",
    bookingUrl: "https://www.visitgrandcanyon.com/trailer-village",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasDumpStation: true,
    amenities: ["Full Hookups", "Inside Grand Canyon NP", "Shuttle Access", "Rim Trails"],
  },
  {
    name: "Campland on the Bay",
    location: "2211 Pacific Beach Dr, San Diego, California",
    city: "San Diego", state: "CA", zipCode: "92109",
    description: "San Diego's premier waterfront RV resort on Mission Bay. Stunning bay views, beach access, watersports rentals, and minutes from SeaWorld and the Pacific Ocean.",
    latitude: 32.7952, longitude: -117.2280,
    imageUrl: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
    websiteUrl: "https://www.campland.com",
    bookingUrl: "https://www.campland.com/reservations",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasPullThrough: true, hasDumpStation: true,
    amenities: ["Bayfront", "Boat Launch", "Watersports", "Pool", "Playground", "Near SeaWorld"],
  },
  {
    name: "Pismo Coast Village RV Resort",
    location: "165 S Dolliver St, Pismo Beach, California",
    city: "Pismo Beach", state: "CA", zipCode: "93449",
    description: "California Central Coast RV resort steps from Pismo Beach and the famous sand dunes. Oceanview sites, full hookups, and direct beach access.",
    latitude: 35.1428, longitude: -120.6412,
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    websiteUrl: "https://www.pismocoastvillage.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasPullThrough: true, hasDumpStation: true,
    amenities: ["Oceanview Sites", "Beach Access", "Pool", "Mini Golf", "Game Room", "Camp Store"],
  },
  {
    name: "Lake Rudolph Campground & RV Resort",
    location: "78 N Holiday Blvd, Santa Claus, Indiana",
    city: "Santa Claus", state: "IN", zipCode: "47579",
    description: "Award-winning family resort next to Holiday World theme park in the famous town of Santa Claus. Water park, planned activities, and full hookups make this a bucket list family destination.",
    latitude: 38.1170, longitude: -86.9138,
    imageUrl: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800",
    websiteUrl: "https://www.lakerudolph.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasPullThrough: true, hasDumpStation: true,
    amenities: ["Waterpark", "Mini Golf", "Next to Holiday World", "Planned Activities", "Camp Store"],
  },
  {
    name: "Ocean Lakes Family Campground",
    location: "6001 S Kings Hwy, Myrtle Beach, South Carolina",
    city: "Myrtle Beach", state: "SC", zipCode: "29575",
    description: "The largest privately owned campground on the East Coast with 859 acres, a mile of beachfront, waterpark, mini golf, and endless activities. A Myrtle Beach institution.",
    latitude: 33.6367, longitude: -78.9745,
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    websiteUrl: "https://www.oceanlakes.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasPullThrough: true, hasDumpStation: true,
    amenities: ["Mile of Beachfront", "Waterpark", "Mini Golf", "Basketball", "Chapel", "Sandy Harbor Water Park"],
  },
  {
    name: "Acadia National Park Blackwoods Campground",
    location: "ME-3, Bar Harbor, Maine",
    city: "Bar Harbor", state: "ME", zipCode: "04609",
    description: "The most popular campground in Acadia National Park with easy access to carriage roads, hiking trails, and the rocky Maine coastline.",
    latitude: 44.3226, longitude: -68.2182,
    imageUrl: "https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=800",
    websiteUrl: "https://www.nps.gov/acad/planyourvisit/blackwoods.htm",
    bookingUrl: "https://www.recreation.gov/camping/campgrounds/233116",
    hasRestrooms: true, hasShowers: true, hasDumpStation: true,
    amenities: ["Inside Acadia NP", "Hiking Trails", "Carriage Roads", "Near Ocean Path"],
  },
  {
    name: "Everglades Isle Motorcoach Resort & Marina",
    location: "803 Collier Ave, Everglades City, Florida",
    city: "Everglades City", state: "FL", zipCode: "34139",
    description: "Luxury Class A motorcoach resort on the edge of the Everglades. Marina access, pool, and guided airboat tours make this a one-of-a-kind Florida RV destination.",
    latitude: 25.8593, longitude: -81.3809,
    imageUrl: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
    websiteUrl: "https://www.evergladesisle.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasDumpStation: true,
    amenities: ["Marina", "Pool", "Airboat Tours", "Fishing", "Kayak Rentals", "Everglades Access"],
  },
  {
    name: "Pirateland Family Camping Resort",
    location: "5401 S Kings Hwy, Myrtle Beach, South Carolina",
    city: "Myrtle Beach", state: "SC", zipCode: "29575",
    description: "Beachfront camping resort on the Grand Strand with direct ocean access, pools, waterslides, and a pirate-themed adventure for the whole family.",
    latitude: 33.6534, longitude: -78.9653,
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    websiteUrl: "https://www.pirateland.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasPullThrough: true, hasDumpStation: true,
    amenities: ["Oceanfront", "Pool", "Waterslides", "Fishing Pier", "Game Room", "Miniature Golf"],
  },
  {
    name: "KOA Williamsburg",
    location: "4000 Newman Rd, Williamsburg, Virginia",
    city: "Williamsburg", state: "VA", zipCode: "23188",
    description: "Award-winning KOA near Colonial Williamsburg and Busch Gardens. Full hookups, heated pool, jumping pillow, and proximity to some of the most historic sites in America.",
    latitude: 37.3271, longitude: -76.7843,
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    websiteUrl: "https://koa.com/campgrounds/williamsburg",
    bookingUrl: "https://koa.com/campgrounds/williamsburg/reserve/",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true,
    amenities: ["Heated Pool", "Jumping Pillow", "Near Colonial Williamsburg", "Near Busch Gardens", "Pancake Breakfast"],
  },
  {
    name: "Bryce Canyon Pines Campground",
    location: "Hwy 12 Mile Marker 10, Bryce, Utah",
    city: "Bryce", state: "UT", zipCode: "84764",
    description: "The closest private campground to Bryce Canyon National Park. Full hookups, store, and stunning red rock views of the canyon country.",
    latitude: 37.6614, longitude: -112.1625,
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
    websiteUrl: "https://www.brycecanyonmotel.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasWifi: true, hasDumpStation: true,
    amenities: ["Full Hookups", "Store", "Near Bryce Canyon NP", "Horseback Riding"],
  },
  {
    name: "Moab Valley RV Resort",
    location: "1773 N US-191, Moab, Utah",
    city: "Moab", state: "UT", zipCode: "84532",
    description: "Premier RV resort in the adventure capital of the Southwest. Steps from Arches and Canyonlands National Parks, with views of red rock mesas from every site.",
    latitude: 38.6072, longitude: -109.5644,
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
    websiteUrl: "https://www.moabvalleyrv.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasPullThrough: true, hasDumpStation: true,
    amenities: ["Pool", "Hot Tub", "Near Arches NP", "Near Canyonlands NP", "WiFi", "Shuttle"],
  },
  {
    name: "Gettysburg Campground",
    location: "2030 Fairfield Rd, Gettysburg, Pennsylvania",
    city: "Gettysburg", state: "PA", zipCode: "17325",
    description: "Historic campground near the Gettysburg battlefield. Full hookups, pool, and guided battlefield tours make this a must-visit for history lovers.",
    latitude: 39.8159, longitude: -77.2892,
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800",
    websiteUrl: "https://www.gettysburgcampground.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true,
    amenities: ["Pool", "Near Gettysburg Battlefield", "Planned Activities", "Camp Store", "WiFi"],
  },
  {
    name: "Gatlinburg Creekside RV Resort",
    location: "1709 E Pkwy, Gatlinburg, Tennessee",
    city: "Gatlinburg", state: "TN", zipCode: "37738",
    description: "Creekside RV resort in the heart of the Smoky Mountains gateway town. Walk to Gatlinburg shops and restaurants, minutes from Great Smoky Mountains National Park.",
    latitude: 35.7143, longitude: -83.4858,
    imageUrl: "https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800",
    websiteUrl: "https://www.gatlinburgcreekside.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasWifi: true,
    hasCableTV: true, hasDumpStation: true,
    amenities: ["Creekside Sites", "WiFi", "Walk to Gatlinburg", "Near Great Smoky Mountains NP"],
  },
  {
    name: "Madeira Beach Municipal Marina & Campground",
    location: "300 Municipal Dr, Madeira Beach, Florida",
    city: "Madeira Beach", state: "FL", zipCode: "33708",
    description: "Florida Gulf Coast waterfront campground with stunning sunset views, fishing pier, and easy beach access. One of the most affordable waterfront camping experiences in Florida.",
    latitude: 27.7978, longitude: -82.7957,
    imageUrl: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
    websiteUrl: "https://www.madeirabeachfl.gov/marina",
    hasElectricHookup: true, hasWaterHookup: true, hasRestrooms: true, hasShowers: true,
    hasDumpStation: true,
    amenities: ["Waterfront", "Fishing Pier", "Beach Access", "Marina", "Sunset Views"],
  },
  {
    name: "Petoskey State Park Campground",
    location: "2475 Harbor-Petoskey Rd, Petoskey, Michigan",
    city: "Petoskey", state: "MI", zipCode: "49770",
    description: "Stunning Great Lakes campground on Little Traverse Bay. Famous for Petoskey stone hunting on the beach and breathtaking northern Michigan sunsets.",
    latitude: 45.4295, longitude: -84.8940,
    imageUrl: "https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=800",
    websiteUrl: "https://www2.dnr.state.mi.us/parksandtrails/Details.aspx?id=471",
    bookingUrl: "https://www.midnrreservations.com",
    hasElectricHookup: true, hasRestrooms: true, hasShowers: true, hasDumpStation: true,
    amenities: ["Lake Michigan Access", "Beach", "Petoskey Stone Hunting", "Hiking Trails"],
  },
  {
    name: "Sun Outdoors Cape Charles",
    location: "32246 Lankford Hwy, Cape Charles, Virginia",
    city: "Cape Charles", state: "VA", zipCode: "23310",
    description: "Chesapeake Bay waterfront resort on the Eastern Shore of Virginia. Multiple pools, lazy river, waterfront sites, and access to the charming town of Cape Charles.",
    latitude: 37.2682, longitude: -76.0194,
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    websiteUrl: "https://www.sunoutdoors.com/virginia/sun-outdoors-cape-charles",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasPullThrough: true, hasDumpStation: true,
    amenities: ["Waterfront", "Lazy River", "Pool", "Kayak Rentals", "Near Cape Charles Town"],
  },
  {
    name: "Crater Lake Resort",
    location: "50711 Hwy 62, Fort Klamath, Oregon",
    city: "Fort Klamath", state: "OR", zipCode: "97626",
    description: "Gateway RV resort to Crater Lake National Park. Full hookups surrounded by Cascades forest, close to the deepest lake in America with its legendary blue waters.",
    latitude: 42.6954, longitude: -122.0451,
    imageUrl: "https://images.unsplash.com/photo-1511576661531-b34d7da5d0bb?w=800",
    websiteUrl: "https://www.craterlakeresort.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasWifi: true,
    hasDumpStation: true,
    amenities: ["Full Hookups", "Near Crater Lake NP", "Fishing", "Hiking Access"],
  },
  {
    name: "Colorado River Motorcoach Resort",
    location: "8311 S Frontage Rd, Parker, Arizona",
    city: "Parker", state: "AZ", zipCode: "85344",
    description: "Premier Class A motorcoach resort on the Colorado River with boat slips, pool, and stunning desert river views. A top destination for water recreation on the lower Colorado.",
    latitude: 34.1478, longitude: -114.2807,
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
    websiteUrl: "https://www.coloradorivermotorcoach.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasDumpStation: true,
    amenities: ["Riverfront", "Boat Slips", "Pool", "Tennis", "Putting Green", "Fitness Center"],
  },
  {
    name: "Lake Guntersville State Park Campground",
    location: "1155 Lodge Dr, Guntersville, Alabama",
    city: "Guntersville", state: "AL", zipCode: "35976",
    description: "Alabama state park campground on beautiful Lake Guntersville. Voted one of the best state park campgrounds in the South with full hookups, beach, and world-class bass fishing.",
    latitude: 34.3620, longitude: -86.2165,
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800",
    websiteUrl: "https://www.alapark.com/parks/lake-guntersville-state-park",
    bookingUrl: "https://reserveamerica.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true,
    hasDumpStation: true,
    amenities: ["Lakefront", "Beach", "Bass Fishing", "Hiking", "Pool", "Golf Course"],
  },
  {
    name: "Riverside RV Park & Resort",
    location: "1386 Ranchero Rd, Oakhurst, California",
    city: "Oakhurst", state: "CA", zipCode: "93644",
    description: "Southern gateway to Yosemite National Park with river access, full hookups, and a peaceful mountain setting. Perfect base camp for exploring Yosemite.",
    latitude: 37.3261, longitude: -119.6490,
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    websiteUrl: "https://www.yosemitervpark.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasDumpStation: true,
    amenities: ["Riverfront", "Pool", "Near Yosemite South Gate", "Full Hookups", "WiFi"],
  },
  {
    name: "Virginia Beach KOA Holiday",
    location: "1240 General Booth Blvd, Virginia Beach, Virginia",
    city: "Virginia Beach", state: "VA", zipCode: "23451",
    description: "Award-winning KOA minutes from Virginia Beach boardwalk and oceanfront. Pool, splash pad, and regular shuttle service to the beach.",
    latitude: 36.7788, longitude: -76.0386,
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    websiteUrl: "https://koa.com/campgrounds/virginia-beach",
    bookingUrl: "https://koa.com/campgrounds/virginia-beach/reserve/",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true,
    amenities: ["Pool", "Splash Pad", "Beach Shuttle", "WiFi", "Near Virginia Beach Boardwalk"],
  },
  {
    name: "Destin West RV Resort",
    location: "4000 Commons Dr W, Destin, Florida",
    city: "Destin", state: "FL", zipCode: "32541",
    description: "Premier RV resort on the Emerald Coast of Florida. Pool, lazy river, and minutes from the sugar-white beaches of Destin and Fort Walton Beach.",
    latitude: 30.3935, longitude: -86.4958,
    imageUrl: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
    websiteUrl: "https://www.destinwestrv.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasPullThrough: true, hasDumpStation: true,
    amenities: ["Pool", "Lazy River", "Near Destin Beach", "WiFi", "Playground"],
  },
  {
    name: "Mackinac Lakeside Campground",
    location: "14737 Mackinaw Hwy, Mackinaw City, Michigan",
    city: "Mackinaw City", state: "MI", zipCode: "49701",
    description: "Lake Michigan waterfront campground with stunning views of the Mackinac Bridge and easy ferry access to Mackinac Island.",
    latitude: 45.7731, longitude: -84.7277,
    imageUrl: "https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=800",
    websiteUrl: "https://www.mackinaclakeside.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasWifi: true,
    hasDumpStation: true,
    amenities: ["Lakefront", "Mackinac Bridge Views", "Ferry Access to Mackinac Island", "Full Hookups"],
  },
  {
    name: "New Orleans West KOA Holiday",
    location: "11129 Jefferson Hwy, River Ridge, Louisiana",
    city: "River Ridge", state: "LA", zipCode: "70123",
    description: "The best base camp for exploring New Orleans. Full hookups, pool, and shuttle service to the French Quarter, Bourbon Street, and world-famous cuisine.",
    latitude: 29.9635, longitude: -90.2183,
    imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800",
    websiteUrl: "https://koa.com/campgrounds/new-orleans",
    bookingUrl: "https://koa.com/campgrounds/new-orleans/reserve/",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true,
    amenities: ["Pool", "Shuttle to French Quarter", "WiFi", "Near New Orleans"],
  },
  {
    name: "Bend Sunriver KOA Resort",
    location: "67265 US-97, Bend, Oregon",
    city: "Bend", state: "OR", zipCode: "97707",
    description: "Central Oregon RV resort near Bend and Sunriver. Volcanic landscape, Mt. Bachelor skiing, and world-class fly fishing and cycling make this a year-round destination.",
    latitude: 43.9037, longitude: -121.4424,
    imageUrl: "https://images.unsplash.com/photo-1511576661531-b34d7da5d0bb?w=800",
    websiteUrl: "https://koa.com/campgrounds/bend-sunriver",
    bookingUrl: "https://koa.com/campgrounds/bend-sunriver/reserve/",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true,
    amenities: ["Pool", "Near Mt. Bachelor", "Fly Fishing", "Cycling Trails", "Near Bend OR"],
  },
  {
    name: "Great Smoky Mountains / Cherokee KOA Holiday",
    location: "92 US-19, Cherokee, North Carolina",
    city: "Cherokee", state: "NC", zipCode: "28719",
    description: "Gateway to Great Smoky Mountains National Park on the Cherokee Reservation. Full hookups, pool, and direct access to hiking, whitewater rafting, and Harrahs Cherokee Casino.",
    latitude: 35.4787, longitude: -83.3099,
    imageUrl: "https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800",
    websiteUrl: "https://koa.com/campgrounds/cherokee",
    bookingUrl: "https://koa.com/campgrounds/cherokee/reserve/",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true,
    amenities: ["Pool", "Near Great Smoky Mountains NP", "Whitewater Rafting", "Near Casino"],
  },
  {
    name: "Shenandoah Valley Campground",
    location: "285 Campground Ln, Luray, Virginia",
    city: "Luray", state: "VA", zipCode: "22835",
    description: "Beautiful Shenandoah Valley campground near Luray Caverns and Shenandoah National Park. Full hookups with stunning Blue Ridge Mountain views.",
    latitude: 38.6648, longitude: -78.4553,
    imageUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    websiteUrl: "https://www.campluray.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasDumpStation: true,
    amenities: ["Pool", "Near Luray Caverns", "Near Shenandoah NP", "Blue Ridge Views"],
  },
  {
    name: "Texas Lakeside RV Resort",
    location: "1201 Lakeview Dr, Waco, Texas",
    city: "Waco", state: "TX", zipCode: "76708",
    description: "Lakeside RV resort near Waco with full hookups and easy access to Magnolia Market at the Silos, Baylor University, and Cameron Park.",
    latitude: 31.5847, longitude: -97.1467,
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800",
    websiteUrl: "https://www.texaslakesidervresort.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasPullThrough: true, hasDumpStation: true,
    amenities: ["Lakefront", "Pool", "Near Magnolia Market", "Full Hookups", "WiFi"],
  },
  {
    name: "Asheville East KOA Holiday",
    location: "2708 Grovestone Rd, Swannanoa, North Carolina",
    city: "Swannanoa", state: "NC", zipCode: "28778",
    description: "Top-rated KOA near Asheville NC, one of America's most beloved mountain cities. Pool, jumping pillow, and easy access to the Blue Ridge Parkway and Biltmore Estate.",
    latitude: 35.5937, longitude: -82.3982,
    imageUrl: "https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800",
    websiteUrl: "https://koa.com/campgrounds/asheville",
    bookingUrl: "https://koa.com/campgrounds/asheville/reserve/",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true,
    amenities: ["Pool", "Jumping Pillow", "Near Blue Ridge Parkway", "Near Biltmore Estate"],
  },
  {
    name: "Sleeping Bear Dunes Campground",
    location: "9922 Front St, Empire, Michigan",
    city: "Empire", state: "MI", zipCode: "49630",
    description: "Gateway campground to Sleeping Bear Dunes National Lakeshore, one of the most scenic spots in Michigan. Massive sand dunes, crystal clear Lake Michigan waters.",
    latitude: 44.8125, longitude: -86.0591,
    imageUrl: "https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=800",
    websiteUrl: "https://www.nps.gov/slbe/planyourvisit/camping.htm",
    bookingUrl: "https://www.recreation.gov",
    hasElectricHookup: true, hasRestrooms: true, hasShowers: true, hasDumpStation: true,
    amenities: ["Near Sleeping Bear Dunes", "Lake Michigan Access", "Hiking", "Swimming"],
  },
  {
    name: "Padre Island National Seashore Campground",
    location: "20420 Park Rd 22, Corpus Christi, Texas",
    city: "Corpus Christi", state: "TX", zipCode: "78418",
    description: "The longest undeveloped barrier island in the world. Primitive and improved sites on the Gulf of Mexico with sea turtle nesting, fishing, and endless beach.",
    latitude: 27.4144, longitude: -97.3798,
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
    websiteUrl: "https://www.nps.gov/pais/planyourvisit/camping.htm",
    bookingUrl: "https://www.recreation.gov",
    hasElectricHookup: true, hasRestrooms: true, hasShowers: true, hasDumpStation: true,
    amenities: ["Gulf of Mexico Beachfront", "Sea Turtle Nesting", "Fishing", "Off-Road Driving", "Primitive Beach Camping"],
  },
  {
    name: "Traverse City KOA Holiday",
    location: "9700 M-37 S, Buckley, Michigan",
    city: "Buckley", state: "MI", zipCode: "49620",
    description: "Northern Michigan KOA near Traverse City, the cherry capital of the world. Pool, planned activities, and proximity to wine country, beaches, and Sleeping Bear Dunes.",
    latitude: 44.5041, longitude: -85.6865,
    imageUrl: "https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?w=800",
    websiteUrl: "https://koa.com/campgrounds/traverse-city",
    bookingUrl: "https://koa.com/campgrounds/traverse-city/reserve/",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true,
    amenities: ["Pool", "Near Traverse City Wine Country", "Near Sleeping Bear Dunes", "Cherry Orchards"],
  },
  {
    name: "Mount Rushmore KOA at Palmer Gulch",
    location: "12620 SD-244, Hill City, South Dakota",
    city: "Hill City", state: "SD", zipCode: "57745",
    description: "The ultimate Black Hills experience, just 5 miles from Mount Rushmore. Water park, horseback riding, nightly hayrides, and stunning views make this a bucket list RV destination.",
    latitude: 43.8782, longitude: -103.5993,
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
    websiteUrl: "https://koa.com/campgrounds/mount-rushmore",
    bookingUrl: "https://koa.com/campgrounds/mount-rushmore/reserve/",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true,
    amenities: ["Water Park", "Horseback Riding", "Hayrides", "Near Mount Rushmore", "Near Crazy Horse Memorial"],
  },
  {
    name: "Flamingo Campground - Everglades National Park",
    location: "1 Flamingo Lodge Hwy, Homestead, Florida",
    city: "Homestead", state: "FL", zipCode: "33034",
    description: "The only campground inside Everglades National Park at the southern tip of Florida. Stunning sunsets over Florida Bay, incredible wildlife, kayaking, and fishing.",
    latitude: 25.1424, longitude: -80.9271,
    imageUrl: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
    websiteUrl: "https://www.nps.gov/ever/planyourvisit/flamcamp.htm",
    bookingUrl: "https://www.recreation.gov",
    hasElectricHookup: true, hasRestrooms: true, hasShowers: true, hasDumpStation: true,
    amenities: ["Inside Everglades NP", "Florida Bay Views", "Kayaking", "Wildlife Viewing", "Fishing"],
  },
  {
    name: "Hot Springs / Black Hills KOA Holiday",
    location: "27585 Hwy 385, Hot Springs, South Dakota",
    city: "Hot Springs", state: "SD", zipCode: "57747",
    description: "Full-service KOA near Wind Cave National Park and the famous hot springs of the Black Hills. Pool, jumping pillow, and proximity to all Black Hills attractions.",
    latitude: 43.3982, longitude: -103.4631,
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
    websiteUrl: "https://koa.com/campgrounds/hot-springs",
    bookingUrl: "https://koa.com/campgrounds/hot-springs/reserve/",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasPullThrough: true, hasDumpStation: true,
    amenities: ["Pool", "Near Wind Cave NP", "Near Hot Springs", "Jumping Pillow"],
  },
  {
    name: "Key West Campground",
    location: "6900 Maloney Ave, Stock Island, Florida",
    city: "Stock Island", state: "FL", zipCode: "33040",
    description: "The southernmost RV campground in the continental US on Stock Island near Key West. Full hookups with tropical views and minutes from Duval Street and all Key West attractions.",
    latitude: 24.5681, longitude: -81.7329,
    imageUrl: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
    websiteUrl: "https://www.keywestcampground.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasPool: true, hasWifi: true,
    hasCableTV: true, hasDumpStation: true,
    amenities: ["Near Key West", "Southernmost Campground", "Pool", "Marina Views", "Near Duval Street"],
  },
  {
    name: "Sedona Pines Resort",
    location: "6701 AZ-89A, Sedona, Arizona",
    city: "Sedona", state: "AZ", zipCode: "86336",
    description: "RV resort in the heart of mystical Sedona surrounded by famous red rock formations. Full hookups with stunning views, near hiking trails, vortex sites, and Tlaquepaque arts district.",
    latitude: 34.9015, longitude: -111.8288,
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
    websiteUrl: "https://www.sedonapines.net",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasWifi: true,
    hasCableTV: true, hasDumpStation: true,
    amenities: ["Red Rock Views", "Near Vortex Sites", "Hiking Trails", "Near Tlaquepaque", "WiFi"],
  },
  {
    name: "Lake Powell Campground & RV Park",
    location: "627 S Lake Powell Blvd, Page, Arizona",
    city: "Page", state: "AZ", zipCode: "86040",
    description: "Gateway RV park to the majestic Lake Powell and Glen Canyon National Recreation Area. Close to Antelope Canyon, Horseshoe Bend, and Rainbow Bridge.",
    latitude: 36.9146, longitude: -111.4559,
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800",
    websiteUrl: "https://www.lakepowellcampground.com",
    hasElectricHookup: true, hasWaterHookup: true, hasSewerHookup: true, hasFullHookups: true,
    hasRestrooms: true, hasShowers: true, hasLaundry: true, hasWifi: true,
    hasDumpStation: true, hasPullThrough: true,
    amenities: ["Near Lake Powell", "Near Antelope Canyon", "Near Horseshoe Bend", "Full Hookups"],
  },
];

async function seedTop50RVParks() {
  console.log("🏕️ Seeding Top 50 Iconic RV Parks...");
  let added = 0;
  let skipped = 0;

  for (const park of TOP_50_RV_PARKS) {
    // Check if already exists by name + state
    const existing = await prisma.campground.findFirst({
      where: {
        name: { equals: park.name, mode: "insensitive" },
        state: park.state,
      },
    });

    if (existing) {
      console.log(`  ⏭️  Already exists: ${park.name}`);
      skipped++;
      continue;
    }

    await prisma.campground.create({
      data: {
        name: park.name,
        location: park.location,
        city: park.city,
        state: park.state,
        zipCode: park.zipCode,
        description: park.description,
        latitude: park.latitude,
        longitude: park.longitude,
        imageUrl: park.imageUrl || null,
        websiteUrl: park.websiteUrl || null,
        bookingUrl: park.bookingUrl || null,
        hasElectricHookup: park.hasElectricHookup || false,
        hasWaterHookup: park.hasWaterHookup || false,
        hasSewerHookup: park.hasSewerHookup || false,
        hasFullHookups: park.hasFullHookups || false,
        hasPullThrough: park.hasPullThrough || false,
        hasBackIn: park.hasBackIn || false,
        hasRestrooms: park.hasRestrooms || false,
        hasShowers: park.hasShowers || false,
        hasLaundry: park.hasLaundry || false,
        hasPool: park.hasPool || false,
        hasDumpStation: park.hasDumpStation || false,
        hasCableTV: park.hasCableTV || false,
        hasPropane: park.hasPropane || false,
        hasWifi: park.hasWifi || false,
        amenities: park.amenities || [],
        verificationStatus: "UNCLAIMED",
      },
    });

    console.log(`  ✅ Added: ${park.name} — ${park.city}, ${park.state}`);
    added++;
  }

  console.log(`\n🎉 Done! Added ${added} new parks, skipped ${skipped} duplicates.`);
}

seedTop50RVParks()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
