[phases.setup]
nixPkgs = []

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["rm -rf dist", "npm run build"]

[start]
cmd = "npm run preview"
# bust cache 1773611445
// 1773623160
// 1773711302
