import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Comprehensive Gas Stations along major interstates
// Data sourced from major truck stop chains
const gasStations = [
  // ==================== I-10 (Southern Route: CA to FL) ====================
  // California
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '1600 W Hobsonway', city: 'Blythe', state: 'CA', zipCode: '92225', latitude: 33.6175, longitude: -114.5964, interstate: 'I-10', exitNumber: '1', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '26999 W Baseline St', city: 'San Bernardino', state: 'CA', zipCode: '92346', latitude: 34.0722, longitude: -117.4017, interstate: 'I-10', exitNumber: '58', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '2685 Lenwood Rd', city: 'Barstow', state: 'CA', zipCode: '92311', latitude: 34.8697, longitude: -117.0228, interstate: 'I-15', exitNumber: '184', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'TA Travel Center', brand: 'TA', address: '48301 National Trails Hwy', city: 'Newberry Springs', state: 'CA', zipCode: '92365', latitude: 34.8306, longitude: -116.6875, interstate: 'I-40', exitNumber: '18', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  
  // Arizona I-10
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '4230 E 22nd St', city: 'Tucson', state: 'AZ', zipCode: '85711', latitude: 32.2056, longitude: -110.8972, interstate: 'I-10', exitNumber: '265', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '3005 S Palo Verde Rd', city: 'Tucson', state: 'AZ', zipCode: '85713', latitude: 32.1856, longitude: -110.9639, interstate: 'I-10', exitNumber: '264', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '1401 N 51st Ave', city: 'Phoenix', state: 'AZ', zipCode: '85043', latitude: 33.4556, longitude: -112.1519, interstate: 'I-10', exitNumber: '139', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'Petro Stopping Center', brand: 'Petro', address: '8230 W Buckeye Rd', city: 'Phoenix', state: 'AZ', zipCode: '85043', latitude: 33.4334, longitude: -112.2289, interstate: 'I-10', exitNumber: '133', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: 'TA Travel Center', brand: 'TA', address: '990 N Pinal Pkwy', city: 'Casa Grande', state: 'AZ', zipCode: '85122', latitude: 32.9089, longitude: -111.7469, interstate: 'I-10', exitNumber: '194', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: "Love's Travel Stop", brand: "Love's", address: '13150 W Gila Bend Hwy', city: 'Buckeye', state: 'AZ', zipCode: '85326', latitude: 33.3706, longitude: -112.5872, interstate: 'I-10', exitNumber: '114', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: false, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '821 E Pima St', city: 'Gila Bend', state: 'AZ', zipCode: '85337', latitude: 32.9478, longitude: -112.7089, interstate: 'I-8', exitNumber: '119', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  
  // New Mexico I-10
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '115 Stern Dr', city: 'Las Cruces', state: 'NM', zipCode: '88001', latitude: 32.3428, longitude: -106.7456, interstate: 'I-10', exitNumber: '139', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '2501 W Amador Ave', city: 'Las Cruces', state: 'NM', zipCode: '88005', latitude: 32.3356, longitude: -106.7978, interstate: 'I-10', exitNumber: '140', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '901 Paisano Dr', city: 'Deming', state: 'NM', zipCode: '88030', latitude: 32.2678, longitude: -107.7531, interstate: 'I-10', exitNumber: '85', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'TA Travel Center', brand: 'TA', address: '2101 W 2nd St', city: 'Lordsburg', state: 'NM', zipCode: '88045', latitude: 32.3467, longitude: -108.7194, interstate: 'I-10', exitNumber: '22', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  
  // Texas I-10
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '8701 Gateway Blvd W', city: 'El Paso', state: 'TX', zipCode: '79925', latitude: 31.7656, longitude: -106.3234, interstate: 'I-10', exitNumber: '28', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '7650 N Desert Blvd', city: 'El Paso', state: 'TX', zipCode: '79912', latitude: 31.8789, longitude: -106.5678, interstate: 'I-10', exitNumber: '6', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '101 E I-10', city: 'Van Horn', state: 'TX', zipCode: '79855', latitude: 31.0394, longitude: -104.8289, interstate: 'I-10', exitNumber: '140', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '2804 E I-10', city: 'Fort Stockton', state: 'TX', zipCode: '79735', latitude: 30.8967, longitude: -102.8456, interstate: 'I-10', exitNumber: '261', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '1601 W Dickinson Blvd', city: 'Fort Stockton', state: 'TX', zipCode: '79735', latitude: 30.8878, longitude: -102.8889, interstate: 'I-10', exitNumber: '259', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'TA Travel Center', brand: 'TA', address: '2501 S Bryant Blvd', city: 'San Angelo', state: 'TX', zipCode: '76903', latitude: 31.4278, longitude: -100.4567, interstate: 'US-87', exitNumber: null, hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '17907 I-10 W', city: 'San Antonio', state: 'TX', zipCode: '78257', latitude: 29.5789, longitude: -98.6234, interstate: 'I-10', exitNumber: '556', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '8815 I-10 E', city: 'San Antonio', state: 'TX', zipCode: '78219', latitude: 29.4289, longitude: -98.3678, interstate: 'I-10', exitNumber: '583', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '15445 I-10 E', city: 'Houston', state: 'TX', zipCode: '77530', latitude: 29.7678, longitude: -95.1234, interstate: 'I-10', exitNumber: '787', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'Petro Stopping Center', brand: 'Petro', address: '5243 E Fwy', city: 'Baytown', state: 'TX', zipCode: '77521', latitude: 29.7567, longitude: -94.9678, interstate: 'I-10', exitNumber: '792', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '5050 I-10 E', city: 'Beaumont', state: 'TX', zipCode: '77705', latitude: 30.0789, longitude: -94.1234, interstate: 'I-10', exitNumber: '851', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  
  // Louisiana I-10
  { name: "Love's Travel Stop", brand: "Love's", address: '1501 N Hwy 171', city: 'Lake Charles', state: 'LA', zipCode: '70615', latitude: 30.2567, longitude: -93.2456, interstate: 'I-10', exitNumber: '36', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '901 N Martin Luther King Hwy', city: 'Lake Charles', state: 'LA', zipCode: '70601', latitude: 30.2389, longitude: -93.2178, interstate: 'I-10', exitNumber: '33', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '3815 NW Evangeline Thwy', city: 'Carencro', state: 'LA', zipCode: '70520', latitude: 30.2978, longitude: -92.0567, interstate: 'I-10', exitNumber: '103', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'TA Travel Center', brand: 'TA', address: '1745 Henderson Hwy', city: 'Breaux Bridge', state: 'LA', zipCode: '70517', latitude: 30.2767, longitude: -91.9056, interstate: 'I-10', exitNumber: '109', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '4545 Airline Hwy', city: 'Baton Rouge', state: 'LA', zipCode: '70805', latitude: 30.4889, longitude: -91.1234, interstate: 'I-10', exitNumber: '155', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '10205 Reiger Rd', city: 'New Orleans', state: 'LA', zipCode: '70129', latitude: 30.0278, longitude: -89.9567, interstate: 'I-10', exitNumber: '246', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: false, hasStore: true, hasPropane: true, hasDumpStation: false },
  
  // Mississippi I-10
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '10552 Three Rivers Rd', city: 'Gulfport', state: 'MS', zipCode: '39503', latitude: 30.4178, longitude: -89.0567, interstate: 'I-10', exitNumber: '34', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '11001 Old Hwy 49', city: 'Wiggins', state: 'MS', zipCode: '39577', latitude: 30.8578, longitude: -89.1356, interstate: 'I-59', exitNumber: '65', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  
  // Alabama I-10
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '1760 S Hwy 59', city: 'Loxley', state: 'AL', zipCode: '36551', latitude: 30.6278, longitude: -87.7456, interstate: 'I-10', exitNumber: '44', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '3555 S Juniper St', city: 'Foley', state: 'AL', zipCode: '36535', latitude: 30.4067, longitude: -87.6856, interstate: 'I-10', exitNumber: '44', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '6530 Theodore Dawes Rd', city: 'Theodore', state: 'AL', zipCode: '36582', latitude: 30.5167, longitude: -88.1956, interstate: 'I-10', exitNumber: '13', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  
  // Florida I-10
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '2995 Pensacola Blvd', city: 'Pensacola', state: 'FL', zipCode: '32505', latitude: 30.4678, longitude: -87.2234, interstate: 'I-10', exitNumber: '12', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '6718 Highway 90', city: 'Milton', state: 'FL', zipCode: '32570', latitude: 30.6078, longitude: -87.0567, interstate: 'I-10', exitNumber: '22', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '2783 W Tennessee St', city: 'Tallahassee', state: 'FL', zipCode: '32304', latitude: 30.4389, longitude: -84.3456, interstate: 'I-10', exitNumber: '196', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '6225 W US Highway 90', city: 'Lake City', state: 'FL', zipCode: '32055', latitude: 30.1878, longitude: -82.6789, interstate: 'I-10', exitNumber: '296', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '350 SW Commerce Dr', city: 'Lake City', state: 'FL', zipCode: '32025', latitude: 30.1689, longitude: -82.6456, interstate: 'I-75', exitNumber: '427', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'TA Travel Center', brand: 'TA', address: '6005 Richard St', city: 'Jacksonville', state: 'FL', zipCode: '32216', latitude: 30.2878, longitude: -81.5456, interstate: 'I-95', exitNumber: '344', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },

  // ==================== I-40 (Central Route: CA to NC) ====================
  // California
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '2615 Lenwood Rd', city: 'Barstow', state: 'CA', zipCode: '92311', latitude: 34.8697, longitude: -117.0228, interstate: 'I-40', exitNumber: '1', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '2959 Lenwood Rd', city: 'Barstow', state: 'CA', zipCode: '92311', latitude: 34.8712, longitude: -117.0182, interstate: 'I-40', exitNumber: '1', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '34580 Yermo Rd', city: 'Yermo', state: 'CA', zipCode: '92398', latitude: 34.9012, longitude: -116.8378, interstate: 'I-15', exitNumber: '191', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '2200 Needles Hwy', city: 'Needles', state: 'CA', zipCode: '92363', latitude: 34.8489, longitude: -114.6178, interstate: 'I-40', exitNumber: '148', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  
  // Arizona I-40
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '2700 E Andy Devine Ave', city: 'Kingman', state: 'AZ', zipCode: '86401', latitude: 35.1894, longitude: -114.0214, interstate: 'I-40', exitNumber: '53', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '3191 E Andy Devine Ave', city: 'Kingman', state: 'AZ', zipCode: '86401', latitude: 35.1912, longitude: -114.0089, interstate: 'I-40', exitNumber: '53', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: false, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'TA Travel Center', brand: 'TA', address: '100 E Bill Williams Ave', city: 'Williams', state: 'AZ', zipCode: '86046', latitude: 35.2512, longitude: -112.1856, interstate: 'I-40', exitNumber: '163', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '801 W Rte 66', city: 'Flagstaff', state: 'AZ', zipCode: '86001', latitude: 35.1956, longitude: -111.6678, interstate: 'I-40', exitNumber: '195', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '5001 E Butler Ave', city: 'Flagstaff', state: 'AZ', zipCode: '86004', latitude: 35.2134, longitude: -111.5567, interstate: 'I-40', exitNumber: '201', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '8500 E Navajo Blvd', city: 'Holbrook', state: 'AZ', zipCode: '86025', latitude: 34.9126, longitude: -110.1152, interstate: 'I-40', exitNumber: '289', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '2815 E Navajo Blvd', city: 'Holbrook', state: 'AZ', zipCode: '86025', latitude: 34.9078, longitude: -110.1456, interstate: 'I-40', exitNumber: '286', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  
  // New Mexico I-40
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '1701 W Historic Hwy 66', city: 'Gallup', state: 'NM', zipCode: '87301', latitude: 35.5186, longitude: -108.7678, interstate: 'I-40', exitNumber: '16', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '2610 W Historic Hwy 66', city: 'Gallup', state: 'NM', zipCode: '87301', latitude: 35.5203, longitude: -108.7821, interstate: 'I-40', exitNumber: '16', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'TA Travel Center', brand: 'TA', address: '100 Frontage Rd', city: 'Grants', state: 'NM', zipCode: '87020', latitude: 35.1478, longitude: -107.8567, interstate: 'I-40', exitNumber: '85', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '5620 University Blvd SE', city: 'Albuquerque', state: 'NM', zipCode: '87106', latitude: 35.0442, longitude: -106.5881, interstate: 'I-40', exitNumber: '222', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '10401 Central Ave NE', city: 'Albuquerque', state: 'NM', zipCode: '87123', latitude: 35.0789, longitude: -106.4567, interstate: 'I-40', exitNumber: '167', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '12950 Central Ave SE', city: 'Albuquerque', state: 'NM', zipCode: '87123', latitude: 35.0623, longitude: -106.4789, interstate: 'I-40', exitNumber: '170', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '109 Dinosaur Trail', city: 'Tucumcari', state: 'NM', zipCode: '88401', latitude: 35.1756, longitude: -103.7089, interstate: 'I-40', exitNumber: '335', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '2501 S Mountain Rd', city: 'Tucumcari', state: 'NM', zipCode: '88401', latitude: 35.1567, longitude: -103.7234, interstate: 'I-40', exitNumber: '332', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  
  // Texas I-40
  { name: "Love's Travel Stop", brand: "Love's", address: '13001 I-40 E', city: 'Amarillo', state: 'TX', zipCode: '79118', latitude: 35.1814, longitude: -101.7139, interstate: 'I-40', exitNumber: '75', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '9101 I-40 E', city: 'Amarillo', state: 'TX', zipCode: '79118', latitude: 35.1823, longitude: -101.7458, interstate: 'I-40', exitNumber: '74', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '2035 Lakeside Dr', city: 'Amarillo', state: 'TX', zipCode: '79110', latitude: 35.1767, longitude: -101.8678, interstate: 'I-40', exitNumber: '62', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'TA Travel Center', brand: 'TA', address: '1600 E Amarillo Blvd', city: 'Amarillo', state: 'TX', zipCode: '79107', latitude: 35.2193, longitude: -101.8089, interstate: 'I-40', exitNumber: '71', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: 'Petro Stopping Center', brand: 'Petro', address: '7900 I-40 W', city: 'Amarillo', state: 'TX', zipCode: '79106', latitude: 35.1878, longitude: -101.9234, interstate: 'I-40', exitNumber: '60', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },

  // Oklahoma I-40
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '2101 S Country Club Rd', city: 'El Reno', state: 'OK', zipCode: '73036', latitude: 35.5034, longitude: -97.9628, interstate: 'I-40', exitNumber: '123', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '7855 S Sooner Rd', city: 'Oklahoma City', state: 'OK', zipCode: '73135', latitude: 35.3842, longitude: -97.3967, interstate: 'I-40', exitNumber: '157', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '6925 S Council Rd', city: 'Oklahoma City', state: 'OK', zipCode: '73169', latitude: 35.3689, longitude: -97.6234, interstate: 'I-40', exitNumber: '140', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'TA Travel Center', brand: 'TA', address: '300 S Choctaw Rd', city: 'Choctaw', state: 'OK', zipCode: '73020', latitude: 35.4878, longitude: -97.2567, interstate: 'I-40', exitNumber: '166', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '4201 Highway 69', city: 'McAlester', state: 'OK', zipCode: '74501', latitude: 34.9267, longitude: -95.7678, interstate: 'I-40', exitNumber: '250', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '1201 S George Nigh Expy', city: 'McAlester', state: 'OK', zipCode: '74501', latitude: 34.9178, longitude: -95.7456, interstate: 'I-40', exitNumber: '250', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },

  // Arkansas I-40
  { name: "Love's Travel Stop", brand: "Love's", address: '1520 Club Rd', city: 'Fort Smith', state: 'AR', zipCode: '72903', latitude: 35.3762, longitude: -94.4281, interstate: 'I-40', exitNumber: '7', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '4201 Phoenix Ave', city: 'Fort Smith', state: 'AR', zipCode: '72903', latitude: 35.3781, longitude: -94.4312, interstate: 'I-40', exitNumber: '7', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '4500 E Broadway', city: 'North Little Rock', state: 'AR', zipCode: '72117', latitude: 34.7956, longitude: -92.2123, interstate: 'I-40', exitNumber: '159', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'TA Travel Center', brand: 'TA', address: '3800 I-40 Service Rd', city: 'North Little Rock', state: 'AR', zipCode: '72117', latitude: 34.7878, longitude: -92.1789, interstate: 'I-40', exitNumber: '161', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: "Love's Travel Stop", brand: "Love's", address: '2700 Dee Ln', city: 'Conway', state: 'AR', zipCode: '72032', latitude: 35.0789, longitude: -92.4234, interstate: 'I-40', exitNumber: '125', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '1405 Museum Rd', city: 'Conway', state: 'AR', zipCode: '72032', latitude: 35.0856, longitude: -92.4567, interstate: 'I-40', exitNumber: '124', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: 'Petro Stopping Center', brand: 'Petro', address: '400 Ingram Blvd', city: 'West Memphis', state: 'AR', zipCode: '72301', latitude: 35.1567, longitude: -90.1678, interstate: 'I-40', exitNumber: '280', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },

  // Tennessee I-40
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '2400 S Highland Ave', city: 'Jackson', state: 'TN', zipCode: '38301', latitude: 35.5789, longitude: -88.8234, interstate: 'I-40', exitNumber: '80', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '5055 Hacks Cross Rd', city: 'Memphis', state: 'TN', zipCode: '38125', latitude: 35.0234, longitude: -89.8567, interstate: 'I-40', exitNumber: '16', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '1475 Vann Dr', city: 'Jackson', state: 'TN', zipCode: '38305', latitude: 35.6278, longitude: -88.7789, interstate: 'I-40', exitNumber: '85', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '250 Stewarts Ferry Pike', city: 'Nashville', state: 'TN', zipCode: '37214', latitude: 36.1678, longitude: -86.6234, interstate: 'I-40', exitNumber: '219', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '125 McGavock Pike', city: 'Nashville', state: 'TN', zipCode: '37214', latitude: 36.1756, longitude: -86.6567, interstate: 'I-40', exitNumber: '216', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'TA Travel Center', brand: 'TA', address: '7021 Strawberry Plains Pike', city: 'Knoxville', state: 'TN', zipCode: '37924', latitude: 36.0123, longitude: -83.7891, interstate: 'I-40', exitNumber: '398', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: 'Petro Stopping Center', brand: 'Petro', address: '7230 Strawberry Plains Pike', city: 'Knoxville', state: 'TN', zipCode: '37924', latitude: 36.0178, longitude: -83.7678, interstate: 'I-40', exitNumber: '398', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },

  // North Carolina I-40
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '100 Starmount Rd', city: 'Asheville', state: 'NC', zipCode: '28806', latitude: 35.5612, longitude: -82.6234, interstate: 'I-40', exitNumber: '44', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '301 Smoky Park Hwy', city: 'Asheville', state: 'NC', zipCode: '28806', latitude: 35.5678, longitude: -82.6567, interstate: 'I-40', exitNumber: '44', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '2700 US-70', city: 'Marion', state: 'NC', zipCode: '28752', latitude: 35.6678, longitude: -81.9789, interstate: 'I-40', exitNumber: '85', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'TA Travel Center', brand: 'TA', address: '3700 Harmon Rd', city: 'Hickory', state: 'NC', zipCode: '28602', latitude: 35.7234, longitude: -81.3456, interstate: 'I-40', exitNumber: '123', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '1405 NC-66', city: 'Kernersville', state: 'NC', zipCode: '27284', latitude: 36.1234, longitude: -80.0567, interstate: 'I-40', exitNumber: '203', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '5211 Market St', city: 'Wilmington', state: 'NC', zipCode: '28405', latitude: 34.2456, longitude: -77.8678, interstate: 'I-40', exitNumber: '420', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },

  // ==================== I-95 (East Coast: FL to ME) ====================
  // Florida
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '3180 SR 207', city: 'St Augustine', state: 'FL', zipCode: '32086', latitude: 29.8234, longitude: -81.3012, interstate: 'I-95', exitNumber: '305', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '125 Outlet Mall Blvd', city: 'Daytona Beach', state: 'FL', zipCode: '32124', latitude: 29.1789, longitude: -81.0456, interstate: 'I-95', exitNumber: '268', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '4545 SR 44', city: 'New Smyrna Beach', state: 'FL', zipCode: '32168', latitude: 29.0234, longitude: -80.9567, interstate: 'I-95', exitNumber: '249', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '4700 W Irlo Bronson Hwy', city: 'Kissimmee', state: 'FL', zipCode: '34746', latitude: 28.3089, longitude: -81.5234, interstate: 'I-4', exitNumber: '64', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '5655 Okeechobee Blvd', city: 'West Palm Beach', state: 'FL', zipCode: '33417', latitude: 26.6878, longitude: -80.1234, interstate: 'I-95', exitNumber: '70', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'TA Travel Center', brand: 'TA', address: '1601 NW 74th St', city: 'Miami', state: 'FL', zipCode: '33147', latitude: 25.8456, longitude: -80.2678, interstate: 'I-95', exitNumber: '12', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },

  // Georgia I-95
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '4626 US Highway 17', city: 'Richmond Hill', state: 'GA', zipCode: '31324', latitude: 31.9234, longitude: -81.3056, interstate: 'I-95', exitNumber: '87', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '1605 US Highway 82', city: 'Brunswick', state: 'GA', zipCode: '31525', latitude: 31.1678, longitude: -81.4789, interstate: 'I-95', exitNumber: '29', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '6640 GA-21', city: 'Port Wentworth', state: 'GA', zipCode: '31407', latitude: 32.1567, longitude: -81.1678, interstate: 'I-95', exitNumber: '109', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  
  // South Carolina I-95
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '195 Campground Rd', city: 'Walterboro', state: 'SC', zipCode: '29488', latitude: 32.9234, longitude: -80.6678, interstate: 'I-95', exitNumber: '57', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '4009 N Jacob Smart Blvd', city: 'Ridgeville', state: 'SC', zipCode: '29472', latitude: 33.0789, longitude: -80.3456, interstate: 'I-95', exitNumber: '68', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '200 Truckstop Rd', city: 'Santee', state: 'SC', zipCode: '29142', latitude: 33.4567, longitude: -80.4789, interstate: 'I-95', exitNumber: '98', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'TA Travel Center', brand: 'TA', address: '500 W Main St', city: 'Turbeville', state: 'SC', zipCode: '29162', latitude: 33.8956, longitude: -79.9234, interstate: 'I-95', exitNumber: '135', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '1001 US-1', city: 'Dillon', state: 'SC', zipCode: '29536', latitude: 34.4234, longitude: -79.3567, interstate: 'I-95', exitNumber: '193', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },

  // North Carolina I-95
  { name: "Love's Travel Stop", brand: "Love's", address: '1050 W 5th St', city: 'Lumberton', state: 'NC', zipCode: '28358', latitude: 34.6267, longitude: -79.0234, interstate: 'I-95', exitNumber: '17', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '2525 Highway 301 N', city: 'Kenly', state: 'NC', zipCode: '27542', latitude: 35.5878, longitude: -78.1234, interstate: 'I-95', exitNumber: '107', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '1001 US-70', city: 'Selma', state: 'NC', zipCode: '27576', latitude: 35.5234, longitude: -78.2789, interstate: 'I-95', exitNumber: '98', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'TA Travel Center', brand: 'TA', address: '350 S King St', city: 'Rocky Mount', state: 'NC', zipCode: '27801', latitude: 35.9267, longitude: -77.8056, interstate: 'I-95', exitNumber: '145', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },

  // Virginia I-95
  { name: "Love's Travel Stop", brand: "Love's", address: '8801 S Military Hwy', city: 'Chesapeake', state: 'VA', zipCode: '23320', latitude: 36.7234, longitude: -76.2678, interstate: 'I-64', exitNumber: '291', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '1301 N Mall Dr', city: 'Petersburg', state: 'VA', zipCode: '23805', latitude: 37.2278, longitude: -77.3789, interstate: 'I-95', exitNumber: '45', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '13500 Jeff Davis Hwy', city: 'Chester', state: 'VA', zipCode: '23836', latitude: 37.3567, longitude: -77.4234, interstate: 'I-95', exitNumber: '61', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'TA Travel Center', brand: 'TA', address: '8500 Brook Rd', city: 'Glen Allen', state: 'VA', zipCode: '23060', latitude: 37.6789, longitude: -77.4678, interstate: 'I-95', exitNumber: '86', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: "Love's Travel Stop", brand: "Love's", address: '12651 Jefferson Davis Hwy', city: 'Fredericksburg', state: 'VA', zipCode: '22407', latitude: 38.2567, longitude: -77.4789, interstate: 'I-95', exitNumber: '126', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '10701 Balls Ford Rd', city: 'Manassas', state: 'VA', zipCode: '20109', latitude: 38.7456, longitude: -77.5234, interstate: 'I-66', exitNumber: '44', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },

  // Maryland I-95
  { name: 'TA Travel Center', brand: 'TA', address: '1101 Elkton Rd', city: 'Newark', state: 'DE', zipCode: '19711', latitude: 39.6234, longitude: -75.7567, interstate: 'I-95', exitNumber: '1', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '4714 Eastern Ave', city: 'Baltimore', state: 'MD', zipCode: '21224', latitude: 39.2878, longitude: -76.5234, interstate: 'I-95', exitNumber: '59', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },

  // New Jersey I-95
  { name: "Love's Travel Stop", brand: "Love's", address: '1 Beckett Rd', city: 'Mount Laurel', state: 'NJ', zipCode: '08054', latitude: 39.9567, longitude: -74.9234, interstate: 'NJ Turnpike', exitNumber: '4', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '975 US-46', city: 'Kearny', state: 'NJ', zipCode: '07032', latitude: 40.7567, longitude: -74.1234, interstate: 'I-95', exitNumber: '15W', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },

  // Connecticut I-95
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '100 Frontage Rd', city: 'Milford', state: 'CT', zipCode: '06460', latitude: 41.2234, longitude: -73.0567, interstate: 'I-95', exitNumber: '40', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },

  // Massachusetts I-95
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '300 Washington St', city: 'Foxborough', state: 'MA', zipCode: '02035', latitude: 42.0567, longitude: -71.2456, interstate: 'I-95', exitNumber: '14', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '1475 Boston Providence Tpke', city: 'Norwood', state: 'MA', zipCode: '02062', latitude: 42.1789, longitude: -71.1234, interstate: 'I-95', exitNumber: '15B', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },

  // ==================== I-80 (Northern Route: CA to NJ) ====================
  // Nebraska
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '5001 K St', city: 'Omaha', state: 'NE', zipCode: '68117', latitude: 41.2134, longitude: -95.9567, interstate: 'I-80', exitNumber: '449', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '3200 S Locust St', city: 'Grand Island', state: 'NE', zipCode: '68801', latitude: 40.8789, longitude: -98.3456, interstate: 'I-80', exitNumber: '312', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '14305 Industrial Rd', city: 'Omaha', state: 'NE', zipCode: '68138', latitude: 41.1567, longitude: -96.0234, interstate: 'I-80', exitNumber: '440', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },

  // Iowa
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '3220 E 53rd St', city: 'Davenport', state: 'IA', zipCode: '52807', latitude: 41.5234, longitude: -90.5456, interstate: 'I-80', exitNumber: '295', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '455 Adventureland Dr NW', city: 'Altoona', state: 'IA', zipCode: '50009', latitude: 41.6456, longitude: -93.4678, interstate: 'I-80', exitNumber: '142', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },

  // Illinois
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '27221 S Dixie Hwy', city: 'Crete', state: 'IL', zipCode: '60417', latitude: 41.4456, longitude: -87.5789, interstate: 'I-57', exitNumber: '327', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '21011 S LaGrange Rd', city: 'Frankfort', state: 'IL', zipCode: '60423', latitude: 41.4789, longitude: -87.8234, interstate: 'I-80', exitNumber: '145', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },

  // Indiana
  { name: "Love's Travel Stop", brand: "Love's", address: '2815 Cassopolis St', city: 'Elkhart', state: 'IN', zipCode: '46514', latitude: 41.6878, longitude: -85.9567, interstate: 'I-80', exitNumber: '92', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'TA Travel Center', brand: 'TA', address: '52246 SR 13', city: 'Middlebury', state: 'IN', zipCode: '46540', latitude: 41.6234, longitude: -85.6789, interstate: 'I-80', exitNumber: '107', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },

  // Ohio
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '940 N Countyline St', city: 'Fostoria', state: 'OH', zipCode: '44830', latitude: 41.1678, longitude: -83.4234, interstate: 'I-80', exitNumber: '91', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '25301 Broadway Ave', city: 'Oakwood Village', state: 'OH', zipCode: '44146', latitude: 41.3789, longitude: -81.5234, interstate: 'I-80', exitNumber: '187', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'Flying J Travel Center', brand: 'Flying J', address: '7990 Reynolds Rd', city: 'Mentor', state: 'OH', zipCode: '44060', latitude: 41.6567, longitude: -81.3456, interstate: 'I-90', exitNumber: '195', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: true },

  // Pennsylvania
  { name: 'Pilot Travel Center', brand: 'Pilot', address: '5400 Interchange Rd', city: 'Lehighton', state: 'PA', zipCode: '18235', latitude: 40.8234, longitude: -75.7567, interstate: 'I-476', exitNumber: '74', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: false },
  { name: "Love's Travel Stop", brand: "Love's", address: '195 Arrowhead Dr', city: 'Bloomsburg', state: 'PA', zipCode: '17815', latitude: 41.0456, longitude: -76.4234, interstate: 'I-80', exitNumber: '232', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: true, hasDumpStation: false },
  { name: 'TA Travel Center', brand: 'TA', address: '255 Sterling Run Dr', city: 'Snow Shoe', state: 'PA', zipCode: '16874', latitude: 41.0234, longitude: -77.9567, interstate: 'I-80', exitNumber: '147', hasDiesel: true, hasTruckParking: true, hasRVParking: true, hasRestrooms: true, hasShowers: true, hasRestaurant: true, hasStore: true, hasPropane: false, hasDumpStation: true },
];

// More Rest Stops
const restStops = [
  // I-10 Rest Stops
  { name: 'Blythe Rest Area', state: 'CA', latitude: 33.6234, longitude: -114.6567, interstate: 'I-10', direction: 'Both', mileMarker: 1, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Arizona Welcome Center', state: 'AZ', latitude: 32.7234, longitude: -114.7234, interstate: 'I-10', direction: 'Westbound', mileMarker: 1, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true, notes: 'Arizona state welcome center with tourist information' },
  { name: 'Sacaton Rest Area', state: 'AZ', latitude: 33.0234, longitude: -111.7456, interstate: 'I-10', direction: 'Both', mileMarker: 175, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Texas Canyon Rest Area', state: 'AZ', latitude: 32.0234, longitude: -110.1234, interstate: 'I-10', direction: 'Both', mileMarker: 318, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true, notes: 'Beautiful rock formations' },
  { name: 'New Mexico Welcome Center', state: 'NM', latitude: 32.0456, longitude: -109.0567, interstate: 'I-10', direction: 'Eastbound', mileMarker: 0, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Deming Rest Area', state: 'NM', latitude: 32.2234, longitude: -107.4567, interstate: 'I-10', direction: 'Both', mileMarker: 102, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Texas Welcome Center', state: 'TX', latitude: 31.7678, longitude: -106.4234, interstate: 'I-10', direction: 'Eastbound', mileMarker: 0, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: true, hasWater: true, is24Hours: true, notes: 'Large Texas travel information center' },
  { name: 'Fort Stockton Rest Area', state: 'TX', latitude: 30.8789, longitude: -102.7234, interstate: 'I-10', direction: 'Both', mileMarker: 264, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Kerrville Rest Area', state: 'TX', latitude: 30.0567, longitude: -99.1234, interstate: 'I-10', direction: 'Both', mileMarker: 505, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Schulenburg Rest Area', state: 'TX', latitude: 29.6789, longitude: -96.9234, interstate: 'I-10', direction: 'Westbound', mileMarker: 674, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Louisiana Welcome Center', state: 'LA', latitude: 30.2234, longitude: -93.8567, interstate: 'I-10', direction: 'Eastbound', mileMarker: 0, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Atchafalaya Basin Rest Area', state: 'LA', latitude: 30.2567, longitude: -91.7456, interstate: 'I-10', direction: 'Both', mileMarker: 115, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true, notes: 'Views of the Atchafalaya Basin swamp' },
  { name: 'Mississippi Welcome Center', state: 'MS', latitude: 30.4234, longitude: -89.5678, interstate: 'I-10', direction: 'Eastbound', mileMarker: 0, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Alabama Welcome Center', state: 'AL', latitude: 30.5234, longitude: -88.0567, interstate: 'I-10', direction: 'Eastbound', mileMarker: 0, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Florida Welcome Center', state: 'FL', latitude: 30.4789, longitude: -87.4234, interstate: 'I-10', direction: 'Eastbound', mileMarker: 0, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: true, hasWater: true, is24Hours: true },

  // I-40 Rest Stops  
  { name: 'Arizona Welcome Center Kingman', state: 'AZ', latitude: 35.2234, longitude: -114.0678, interstate: 'I-40', direction: 'Eastbound', mileMarker: 48, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Meteor Crater Rest Area', state: 'AZ', latitude: 35.0289, longitude: -111.0234, interstate: 'I-40', direction: 'Both', mileMarker: 233, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: false, is24Hours: true, notes: 'Near Meteor Crater National Landmark' },
  { name: 'Painted Desert Rest Area', state: 'AZ', latitude: 35.0789, longitude: -109.7567, interstate: 'I-40', direction: 'Both', mileMarker: 311, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true, notes: 'Scenic views of the Painted Desert' },
  { name: 'Continental Divide Rest Area', state: 'NM', latitude: 35.4234, longitude: -108.3456, interstate: 'I-40', direction: 'Both', mileMarker: 47, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true, notes: 'At the Continental Divide - 7,245 ft elevation' },
  { name: 'Rio Puerco Rest Area', state: 'NM', latitude: 35.0567, longitude: -106.9234, interstate: 'I-40', direction: 'Both', mileMarker: 140, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Clines Corners Rest Area', state: 'NM', latitude: 35.0123, longitude: -105.5234, interstate: 'I-40', direction: 'Both', mileMarker: 218, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Texas Welcome Center Amarillo', state: 'TX', latitude: 35.2189, longitude: -102.0567, interstate: 'I-40', direction: 'Eastbound', mileMarker: 0, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: true, hasWater: true, is24Hours: true },
  { name: 'Adrian Rest Area', state: 'TX', latitude: 35.2734, longitude: -102.6678, interstate: 'I-40', direction: 'Both', mileMarker: 22, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true, notes: 'Near the midpoint of Route 66' },
  { name: 'Oklahoma Welcome Center', state: 'OK', latitude: 35.2134, longitude: -99.9678, interstate: 'I-40', direction: 'Eastbound', mileMarker: 1, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Sayre Rest Area', state: 'OK', latitude: 35.2789, longitude: -99.6234, interstate: 'I-40', direction: 'Both', mileMarker: 20, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Oklahoma City Rest Area', state: 'OK', latitude: 35.4012, longitude: -97.5234, interstate: 'I-40', direction: 'Both', mileMarker: 149, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Arkansas Welcome Center', state: 'AR', latitude: 35.3567, longitude: -94.4234, interstate: 'I-40', direction: 'Eastbound', mileMarker: 1, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Ozark Rest Area', state: 'AR', latitude: 35.4567, longitude: -93.8234, interstate: 'I-40', direction: 'Both', mileMarker: 35, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Russellville Rest Area', state: 'AR', latitude: 35.2678, longitude: -93.1234, interstate: 'I-40', direction: 'Eastbound', mileMarker: 84, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Tennessee Welcome Center', state: 'TN', latitude: 35.0456, longitude: -90.0234, interstate: 'I-40', direction: 'Eastbound', mileMarker: 1, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Jackson Rest Area', state: 'TN', latitude: 35.6234, longitude: -88.8012, interstate: 'I-40', direction: 'Both', mileMarker: 82, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Cookeville Rest Area', state: 'TN', latitude: 36.1345, longitude: -85.5012, interstate: 'I-40', direction: 'Both', mileMarker: 290, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: true, hasWater: true, is24Hours: true },
  { name: 'North Carolina Welcome Center', state: 'NC', latitude: 35.6234, longitude: -83.2567, interstate: 'I-40', direction: 'Eastbound', mileMarker: 1, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Asheville Rest Area', state: 'NC', latitude: 35.5912, longitude: -82.5534, interstate: 'I-40', direction: 'Both', mileMarker: 55, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Hickory Rest Area', state: 'NC', latitude: 35.7234, longitude: -81.3456, interstate: 'I-40', direction: 'Eastbound', mileMarker: 123, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },

  // I-95 Rest Stops
  { name: 'Florida Welcome Center Jacksonville', state: 'FL', latitude: 30.3567, longitude: -81.5234, interstate: 'I-95', direction: 'Southbound', mileMarker: 373, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'St Augustine Rest Area', state: 'FL', latitude: 29.9234, longitude: -81.3456, interstate: 'I-95', direction: 'Both', mileMarker: 311, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Flagler Rest Area', state: 'FL', latitude: 29.4678, longitude: -81.1234, interstate: 'I-95', direction: 'Both', mileMarker: 284, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Georgia Welcome Center', state: 'GA', latitude: 30.7234, longitude: -81.5678, interstate: 'I-95', direction: 'Northbound', mileMarker: 1, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Savannah Rest Area', state: 'GA', latitude: 32.0123, longitude: -81.0234, interstate: 'I-95', direction: 'Both', mileMarker: 109, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'South Carolina Welcome Center', state: 'SC', latitude: 32.3456, longitude: -81.0567, interstate: 'I-95', direction: 'Northbound', mileMarker: 1, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Santee Rest Area', state: 'SC', latitude: 33.4234, longitude: -80.4567, interstate: 'I-95', direction: 'Both', mileMarker: 97, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true, notes: 'Near Lake Marion' },
  { name: 'North Carolina Welcome Center', state: 'NC', latitude: 34.3234, longitude: -79.0678, interstate: 'I-95', direction: 'Northbound', mileMarker: 1, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Fayetteville Rest Area', state: 'NC', latitude: 35.0789, longitude: -78.9234, interstate: 'I-95', direction: 'Both', mileMarker: 56, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: false, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Virginia Welcome Center', state: 'VA', latitude: 36.5567, longitude: -77.4234, interstate: 'I-95', direction: 'Northbound', mileMarker: 1, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Fredericksburg Rest Area', state: 'VA', latitude: 38.2234, longitude: -77.5234, interstate: 'I-95', direction: 'Both', mileMarker: 118, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Dale City Rest Area', state: 'VA', latitude: 38.6234, longitude: -77.3234, interstate: 'I-95', direction: 'Both', mileMarker: 156, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Maryland Welcome Center', state: 'MD', latitude: 39.0567, longitude: -76.7234, interstate: 'I-95', direction: 'Northbound', mileMarker: 37, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Delaware Welcome Center', state: 'DE', latitude: 39.5567, longitude: -75.7234, interstate: 'I-95', direction: 'Northbound', mileMarker: 1, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'New Jersey Welcome Center', state: 'NJ', latitude: 39.6567, longitude: -75.5234, interstate: 'NJ Turnpike', direction: 'Northbound', mileMarker: 1, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
  { name: 'Clara Barton Service Area', state: 'NJ', latitude: 40.0567, longitude: -74.7234, interstate: 'NJ Turnpike', direction: 'Both', mileMarker: 44, hasRestrooms: true, hasPicnicArea: false, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: false, is24Hours: true, notes: 'Full service plaza' },
  { name: 'Connecticut Welcome Center', state: 'CT', latitude: 41.1567, longitude: -73.2234, interstate: 'I-95', direction: 'Northbound', mileMarker: 13, hasRestrooms: true, hasPicnicArea: true, hasPetArea: true, hasVending: true, hasWifi: true, hasRVParking: true, hasDumpStation: false, hasWater: true, is24Hours: true },
];

async function seedMoreRoadtripData() {
  console.log('🚗 Seeding additional roadtrip data...');

  // Clear existing data first to avoid duplicates
  console.log('🧹 Clearing existing gas stations and rest stops...');
  await prisma.gasStation.deleteMany({});
  await prisma.restStop.deleteMany({});

  // Seed gas stations
  console.log('⛽ Seeding gas stations...');
  let stationCount = 0;
  for (const station of gasStations) {
    try {
      await prisma.gasStation.create({ data: station });
      stationCount++;
    } catch (error) {
      console.error(`Failed to create station: ${station.name}`, error);
    }
  }
  console.log(`   ✅ ${stationCount} gas stations seeded`);

  // Seed rest stops
  console.log('🅿️ Seeding rest stops...');
  let stopCount = 0;
  for (const stop of restStops) {
    try {
      await prisma.restStop.create({ data: stop });
      stopCount++;
    } catch (error) {
      console.error(`Failed to create rest stop: ${stop.name}`, error);
    }
  }
  console.log(`   ✅ ${stopCount} rest stops seeded`);

  console.log('🎉 Additional roadtrip data seeding complete!');
  console.log(`   Total: ${stationCount} gas stations, ${stopCount} rest stops`);
}

// Run directly if called as script
seedMoreRoadtripData()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
